workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/ios --legacy-peer-deps
          npx cap sync ios
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/build/App.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/App.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build/ios/ipa
    artifacts:
      - build/ios/ipa