import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations = {
  en: {
    // Auth
    'auth.selectRole': 'Select Your Role',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.welcomeBack': 'Welcome Back',
    'auth.loginSubtitle': 'Enter your credentials to access your account',
    
    // Roles
    'role.admin': 'Administrator',
    'role.teacher': 'Teacher',
    'role.parent': 'Parent',
    'role.student': 'Student',
    'role.driver': 'Driver',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Home Page',
    'dashboard.students': 'Students',
    'dashboard.teachers': 'Teachers',
    'dashboard.classes': 'Classes',
    'dashboard.attendance': 'Attendance',
    'dashboard.finance': 'Finance',
    'dashboard.transport': 'Transportation',
    'dashboard.canteen': 'Canteen',
    'dashboard.messages': 'Messages',
    'dashboard.settings': 'Settings',
    'dashboard.reports': 'Reports',
    'dashboard.schedule': 'Schedule',
    'dashboard.homework': 'Homework',
    'dashboard.grades': 'Grades',
    'dashboard.examSchedule': 'Exam Schedule',
    'dashboard.wallet': 'Wallet',
    'dashboard.kitchen': 'School Kitchen',
    'dashboard.tracking': 'Bus Tracking',
    'dashboard.profile': 'Profile',
    'dashboard.store': 'Store',
    'dashboard.feeManagement': 'Fee Management',
    'dashboard.parentFinance': 'Parent Finance',
    'dashboard.payroll': 'Payroll',
    'dashboard.userManagement': 'User Management',
    'dashboard.nfcManagement': 'NFC Management',
    
    // Parent Dashboard
    'parent.welcome': 'Welcome',
    'parent.monitorChildren': 'Monitor your children\'s academic progress and school activities',
    'parent.viewProfile': 'View Full Profile',
    'parent.trackBus': 'Track Bus',
    'parent.wallet': 'Wallet',
    'parent.payFees': 'Pay Fees',
    'parent.canteen': 'Canteen',
    'parent.todaySchedule': 'Today\'s Schedule',
    'parent.busStatus': 'Bus Status',
    'parent.feeStatus': 'Fee Status',
    'parent.morningPickup': 'Morning Pickup',
    'parent.afternoonDrop': 'Afternoon Drop',
    'parent.trackLive': 'Track Live',
    'parent.totalFees': 'Total Fees',
    'parent.paid': 'Paid',
    'parent.remaining': 'Remaining',
    'parent.payNow': 'Pay Now',
    'parent.attendance': 'Attendance',
    'parent.averageGrade': 'Average Grade',
    'parent.dailyAllowance': 'Daily Allowance',
    'parent.todaySpending': 'Today\'s Spending',
    'parent.grade': 'Grade',
    'parent.setHomeLocation': 'Set Home Location',
    'parent.store': 'School Store',
    
    // Students & Teachers
    'students.manageProfiles': 'Manage and view all student profiles',
    'students.searchPlaceholder': 'Search by name, NFC, or barcode...',
    'students.addStudent': 'Add Student',
    'students.viewFullProfile': 'View Full Profile',
    'students.editProfile': 'Edit Student Profile',
    'students.scanBarcode': 'Scan Barcode',
    'students.studentProfile': 'Student Profile',
    'students.readNFC': 'Read NFC',
    'students.readingNFC': 'Reading NFC Card...',
    'students.tapCard': 'Please tap the NFC card',
    'students.nfcSuccess': 'NFC Read Successful',
    'students.foundStudent': 'Found student',
    'teachers.manageProfiles': 'Manage and view all teacher profiles',
    'teachers.searchPlaceholder': 'Search by name or email...',
    'teachers.addTeacher': 'Add Teacher',
    'teachers.viewProfile': 'View Profile',
    'teachers.editProfile': 'Edit Teacher Profile',
    'teachers.createEmail': 'Create Email',
    'teachers.qualification': 'Qualification',
    'teachers.experience': 'Experience',
    'teachers.joinDate': 'Join Date',
    'teachers.subjects': 'Subjects',
    
    // Attendance
    'attendance.trackAttendance': 'Track student attendance in school and bus',
    'attendance.records': 'Attendance Records',
    'attendance.all': 'All',
    'attendance.school': 'School',
    'attendance.bus': 'Bus',
    'attendance.present': 'Present',
    'attendance.absent': 'Absent',
    'attendance.late': 'Late',
    'attendance.presentDays': 'Present Days',
    'attendance.absentDays': 'Absent Days',
    'attendance.lateDays': 'Late Days',
    'attendance.rate': 'Attendance Rate',
    'attendance.scanNFC': 'Scan NFC',
    'attendance.scanningNFC': 'Scanning NFC Card...',
    'attendance.tapStudent': 'Please tap the student card',
    'attendance.recorded': 'Attendance Recorded',
    'attendance.checkedIn': 'Student checked in successfully',
    
    // Driver specific
    'driver.dashboard': 'Driver Dashboard',
    'driver.route': 'Route',
    'driver.morningRoute': 'Morning Route',
    'driver.afternoonRoute': 'Afternoon Route',
    'driver.vehicle': 'Vehicle',
    'driver.students': 'Students',
    'driver.eta': 'ETA',
    'driver.toSchool': 'To school',
    'driver.nextStop': 'Next Stop',
    'driver.routeMap': 'Route Map',
    'driver.startNavigation': 'Start Navigation',
    'driver.studentPickupStatus': 'Student Pickup Status',
    'driver.quickActions': 'Quick Actions',
    'driver.markAbsent': 'Mark Student Absent',
    'driver.reportDelay': 'Report Delay',
    'driver.emergencyContact': 'Emergency Contact',
    'driver.endRoute': 'End Route',
    'driver.startRoute': 'Start Route',
    'driver.pauseRoute': 'Pause',
    'driver.resumeRoute': 'Resume',
    'driver.pickUp': 'Pick Up',
    'driver.absent': 'Absent',
    'driver.lowFuelAlert': 'Low Fuel Alert',
    'driver.trafficDelay': 'Traffic Delay',
    'driver.arrivedAtSchool': 'Arrived at School',
    'driver.progress': 'Progress',
    'driver.tracking': 'Tracking',
    'driver.offline': 'Offline',
    'driver.routeTracking': 'Route Tracking',
    'driver.liveLocation': 'Live Location',
    'driver.currentLocation': 'Current Location',
    'driver.studentList': 'Student List',
    'driver.report': 'Report',
    'driver.sendReport': 'Send Report',
    'driver.reportType': 'Report Type',
    'driver.routeDelay': 'Route Delay',
    'driver.incidentReport': 'Incident Report',
    'driver.mechanicalIssue': 'Mechanical Issue',
    'driver.other': 'Other',
    'driver.message': 'Message',
    'driver.describeIssue': 'Describe the issue...',
    'driver.waiting': 'Waiting',
    'driver.pickedUp': 'Picked Up',
    'driver.droppedOff': 'Dropped Off',
    
    // Transport
    'transport.manage': 'Manage school transportation and buses',
    'transport.addBus': 'Add Bus',
    'transport.totalBuses': 'Total Buses',
    'transport.activeBuses': 'Active Buses',
    'transport.totalCapacity': 'Total Capacity',
    'transport.currentStudents': 'Current Students',
    'transport.students': 'Students',
    'transport.lastLocation': 'Last Location',
    'transport.updated': 'Updated',
    'transport.route': 'Route',
    'transport.editBus': 'Edit Bus Information',
    'transport.driverName': 'Driver Name',
    'transport.driverPhone': 'Driver Phone',
    'transport.busNumber': 'Bus Number',
    
    // Common
    'common.language': 'Language',
    'common.english': 'English',
    'common.arabic': 'العربية',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.close': 'Close',
    'common.currency': 'OMR',
    'common.name': 'Name',
    'common.nameAr': 'Name (Arabic)',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.class': 'Class',
    'common.address': 'Address',
    'common.bloodGroup': 'Blood Group',
    'common.allergies': 'Allergies',
    'common.emergencyContact': 'Emergency Contact',
    'common.dateOfBirth': 'Date of Birth',
    'common.parentName': 'Parent Name',
    'common.parentPhone': 'Parent Phone',
    'common.notes': 'Notes',
    'common.importantNotes': 'Important Notes',
    'common.contactInfo': 'Contact Information',
    'common.homeAddress': 'Home Address',
    'common.viewOnMap': 'View on Map',
    'common.call': 'Call',
    'common.maintenance': 'Maintenance',
    'common.capacity': 'Capacity',
    'common.subject': 'Subject',
    'common.teacher': 'Teacher',
    'common.room': 'Room',
    'common.day': 'Day',
    'common.duration': 'Duration',
    'common.examType': 'Exam Type',
    'common.newMessage': 'New Message',
    'common.typeMessage': 'Type your message...',
    'common.selectConversation': 'Select a conversation to start messaging',
    'common.messageSent': 'Message Sent',
    'common.messageSentDesc': 'Your message has been sent successfully',
    'common.searchConversations': 'Search conversations...',
    'common.calendar': 'Calendar',
    'common.deleted': 'Deleted',
    'common.deletedDesc': 'Item deleted successfully',
    'common.savedSuccessfully': 'Saved successfully',
    'common.profileUpdated': 'Profile updated successfully',
    'common.welcomeDashboard': 'Welcome back to your school management dashboard',
    'common.fromLastMonth': 'from last month',
    'common.recentActivities': 'Recent Activities',
    'common.upcomingEvents': 'Upcoming Events',
    'common.morningRoute': 'Morning Route',
    'common.parentContact': 'Parent Contact',
    'common.homeLocation': 'Home Location',
    'common.openInMaps': 'Open in Maps',
    'common.studentInfo': 'Student Information',
    'common.addClass': 'Add Class',
    'common.classTeacher': 'Class Teacher',
    'common.classesToday': 'Classes Today',
    'common.classSchedule': 'Class Schedule',
    'common.examSchedule': 'Exam Schedule',
    'common.addSchedule': 'Add Schedule',
    'common.addExam': 'Add Exam',
    'common.addClassSchedule': 'Add Class Schedule',
    'common.addExamSchedule': 'Add Exam Schedule',
    'common.emailCreated': 'Email Account Created',
    'common.emailCreatedDesc': 'Email account has been created successfully',
    'common.noPermission': 'You don\'t have permission to view this page',
    'common.manageClasses': 'Manage class schedules and exams',
    'common.communicateStaff': 'Communicate with teachers and school staff',
    'common.driverDashboard': 'Driver Dashboard',
    'common.busRouteManagement': 'Bus route management and student tracking',
    'common.teacherDashboard': 'Teacher Dashboard',
    'common.manageYourClasses': 'Manage your classes and track student progress',
    'common.barcode': 'Barcode',
    'common.nfcId': 'NFC ID',
    'common.rollNumber': 'Roll Number',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.available': 'Available',
    'common.notAvailable': 'Not Available',
    'common.id': 'ID',
    'common.grade': 'Grade',
    'common.section': 'Section',
    'common.viewDetails': 'View Details',
    'common.noRecords': 'No records found',
    'common.noStudentsOnboard': 'No students onboard',
    'common.noRecordsToday': 'No records yet today',
    
    // Footer
    'footer.allRightsReserved': 'All rights reserved',
    
    // Log levels
    'log.info': 'INFO',
    'log.warn': 'WARN', 
    'log.error': 'ERROR',
    'log.debug': 'DEBUG',
    
    // Status badges
    'status.draft': 'Draft',
    'status.pendingApproval': 'Pending Approval',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.available': 'Available',
    'status.notAvailable': 'Not Available',
    'status.present': 'Present',
    'status.absent': 'Absent',
    'status.late': 'Late',
    'status.notMarked': 'Not Marked',
    
    // Stats
    'stats.totalStudents': 'Total Students',
    'stats.totalTeachers': 'Total Teachers',
    'stats.attendance': 'Attendance Rate',
    'stats.busesActive': 'Active Buses',
    'stats.pendingFees': 'Pending Fees',
    
    // Features
    'feature.busTracking': 'Bus Tracking',
    'feature.wallet': 'Digital Wallet',
    'feature.payments': 'Payments',
    'feature.canteen': 'Canteen Management',
    
    // Schedule
    'schedule.mathematics': 'Mathematics',
    'schedule.physics': 'Physics',
    'schedule.english': 'English',
    'schedule.arabic': 'Arabic',
    'schedule.chemistry': 'Chemistry',
    'schedule.history': 'History',
    'schedule.pe': 'PE',
    'schedule.break': 'Break',
    'schedule.room': 'Room',
    'schedule.lab': 'Lab',
    'schedule.canteen': 'Canteen',
    'schedule.sportsHall': 'Sports Hall',
    'schedule.downloadSchedule': 'Download Schedule',
    'schedule.todaySchedule': "Today's Schedule",
    'schedule.scheduleSummary': 'Schedule Summary',
    'schedule.classes': 'Classes',
    'schedule.totalHours': 'Total Hours',
    'schedule.manageSchedules': 'View and manage daily schedules',
    
    // Grades
    'grades.subject': 'Subject',
    'grades.grade': 'Grade',
    'grades.score': 'Score',
    'grades.date': 'Date',
    'grades.teacher': 'Teacher',
    'grades.exam': 'Exam',
    'grades.assignment': 'Assignment',
    'grades.project': 'Project',
    'grades.midterm': 'Midterm',
    'grades.final': 'Final',
    'grades.quiz': 'Quiz',
    'grades.homework': 'Homework',
    'grades.classwork': 'Classwork',
    'grades.recentGrades': 'Recent Grades',
    'grades.examType': 'Exam Type',
    'grades.notes': 'Notes',
    'grades.approve': 'Approve',
    'grades.addGrade': 'Add Grade',
    'grades.editGrade': 'Edit Grade',
    'grades.selectClass': 'Select Class',
    'grades.selectStudent': 'Select Student',
    'grades.selectSubject': 'Select Subject',
    'grades.enterScore': 'Enter Score',
    'grades.enterNotes': 'Enter Notes',
    
    // Homework
    'homework.pendingHomework': 'Pending Homework',
    'homework.dueDate': 'Due Date',
    'homework.submit': 'Submit',
    'homework.submitted': 'Submitted',
    'homework.notSubmitted': 'Not Submitted',
    
    // Exams
    'exams.upcomingExams': 'Upcoming Exams',
    'exams.examDate': 'Exam Date',
    'exams.examTime': 'Exam Time',
    'exams.examLocation': 'Exam Location',
    
    // Time
    'time.minutes': 'minutes',
    'time.hours': 'hours',
    'time.days': 'days',
    'time.ago': 'ago',
    'time.min': 'min',
    'time.hrs': 'hrs',
    
    // Student Profile
    'profile.studentWallet': 'Student Wallet',
    'profile.studentHomework': 'Student Homework',
    'profile.studentNotes': 'Notes',
    'profile.studentSchedules': 'Schedules',
    'profile.viewGrades': 'View Grades',
    'profile.manageWallet': 'Manage Wallet',
  },
  ar: {
    // Auth
    'auth.selectRole': 'اختر دورك',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.loginSubtitle': 'أدخل بيانات الاعتماد الخاصة بك للوصول إلى حسابك',
    
    // Roles
    'role.admin': 'المدير',
    'role.teacher': 'المعلم',
    'role.parent': 'ولي الأمر',
    'role.student': 'الطالب',
    'role.driver': 'السائق',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.overview': 'الصفحة الرئيسية',
    'dashboard.students': 'الطلاب',
    'dashboard.teachers': 'المعلمون',
    'dashboard.classes': 'الفصول',
    'dashboard.attendance': 'الحضور',
    'dashboard.finance': 'المالية',
    'dashboard.transport': 'النقل',
    'dashboard.canteen': 'المقصف',
    'dashboard.messages': 'الرسائل',
    'dashboard.settings': 'الإعدادات',
    'dashboard.reports': 'التقارير',
    'dashboard.schedule': 'الجدول',
    'dashboard.homework': 'الواجبات',
    'dashboard.grades': 'الدرجات',
    'dashboard.examSchedule': 'جدول الامتحانات',
    'dashboard.wallet': 'المحفظة',
    'dashboard.kitchen': 'مطبخ المدرسة',
    'dashboard.tracking': 'تتبع الحافلة',
    'dashboard.profile': 'الملف الشخصي',
    'dashboard.store': 'المتجر',
    'dashboard.feeManagement': 'إدارة الرسوم',
    'dashboard.parentFinance': 'المالية للوالدين',
    'dashboard.payroll': 'الرواتب',
    'dashboard.userManagement': 'إدارة المستخدمين',
    'dashboard.nfcManagement': 'إدارة NFC',
    
    // Parent Dashboard
    'parent.welcome': 'مرحباً',
    'parent.monitorChildren': 'راقب التقدم الأكاديمي لأطفالك والأنشطة المدرسية',
    'parent.viewProfile': 'عرض الملف الكامل',
    'parent.trackBus': 'تتبع الحافلة',
    'parent.wallet': 'المحفظة',
    'parent.payFees': 'دفع الرسوم',
    'parent.canteen': 'المقصف',
    'parent.todaySchedule': 'جدول اليوم',
    'parent.busStatus': 'حالة الحافلة',
    'parent.feeStatus': 'حالة الرسوم',
    'parent.morningPickup': 'الاستلام الصباحي',
    'parent.afternoonDrop': 'التوصيل بعد الظهر',
    'parent.trackLive': 'تتبع مباشر',
    'parent.totalFees': 'إجمالي الرسوم',
    'parent.paid': 'مدفوع',
    'parent.remaining': 'متبقي',
    'parent.payNow': 'ادفع الآن',
    'parent.attendance': 'الحضور',
    'parent.averageGrade': 'متوسط الدرجة',
    'parent.dailyAllowance': 'المصروف اليومي',
    'parent.todaySpending': 'مصروف اليوم',
    'parent.grade': 'الصف',
    'parent.setHomeLocation': 'تحديد موقع المنزل',
    'parent.store': 'المتجر المدرسي',
    
    // Students & Teachers
    'students.manageProfiles': 'إدارة وعرض جميع ملفات الطلاب',
    'students.searchPlaceholder': 'البحث بالاسم أو NFC أو الباركود...',
    'students.addStudent': 'إضافة طالب',
    'students.viewFullProfile': 'عرض الملف الكامل',
    'students.editProfile': 'تعديل ملف الطالب',
    'students.scanBarcode': 'مسح الباركود',
    'students.studentProfile': 'ملف الطالب',
    'students.readNFC': 'قراءة NFC',
    'students.readingNFC': 'قراءة بطاقة NFC...',
    'students.tapCard': 'يرجى تقريب بطاقة NFC',
    'students.nfcSuccess': 'تمت قراءة NFC بنجاح',
    'students.foundStudent': 'تم العثور على الطالب',
    'teachers.manageProfiles': 'إدارة وعرض جميع ملفات المعلمين',
    'teachers.searchPlaceholder': 'البحث بالاسم أو البريد الإلكتروني...',
    'teachers.addTeacher': 'إضافة معلم',
    'teachers.viewProfile': 'عرض الملف',
    'teachers.editProfile': 'تعديل ملف المعلم',
    'teachers.createEmail': 'إنشاء بريد',
    'teachers.qualification': 'المؤهل',
    'teachers.experience': 'الخبرة',
    'teachers.joinDate': 'تاريخ الانضمام',
    'teachers.subjects': 'المواد',
    
    // Attendance
    'attendance.trackAttendance': 'تتبع حضور الطلاب في المدرسة والحافلة',
    'attendance.records': 'سجلات الحضور',
    'attendance.all': 'الكل',
    'attendance.school': 'المدرسة',
    'attendance.bus': 'الحافلة',
    'attendance.present': 'حاضر',
    'attendance.absent': 'غائب',
    'attendance.late': 'متأخر',
    'attendance.presentDays': 'أيام الحضور',
    'attendance.absentDays': 'أيام الغياب',
    'attendance.lateDays': 'أيام التأخير',
    'attendance.rate': 'معدل الحضور',
    'attendance.scanNFC': 'مسح NFC',
    'attendance.scanningNFC': 'مسح بطاقة NFC...',
    'attendance.tapStudent': 'يرجى تقريب بطاقة الطالب',
    'attendance.recorded': 'تم تسجيل الحضور',
    'attendance.checkedIn': 'تم تسجيل حضور الطالب بنجاح',
    
    // Driver specific
    'driver.dashboard': 'لوحة تحكم السائق',
    'driver.route': 'المسار',
    'driver.morningRoute': 'الرحلة الصباحية',
    'driver.afternoonRoute': 'رحلة بعد الظهر',
    'driver.vehicle': 'المركبة',
    'driver.students': 'الطلاب',
    'driver.eta': 'الوقت المتوقع للوصول',
    'driver.toSchool': 'إلى المدرسة',
    'driver.nextStop': 'المحطة التالية',
    'driver.routeMap': 'خريطة المسار',
    'driver.startNavigation': 'بدء الملاحة',
    'driver.studentPickupStatus': 'حالة استلام الطلاب',
    'driver.quickActions': 'الإجراءات السريعة',
    'driver.markAbsent': 'تسجيل غياب طالب',
    'driver.reportDelay': 'الإبلاغ عن تأخير',
    'driver.emergencyContact': 'الاتصال الطارئ',
    'driver.endRoute': 'إنهاء الرحلة',
    'driver.startRoute': 'بدء المسار',
    'driver.pauseRoute': 'إيقاف مؤقت',
    'driver.resumeRoute': 'استئناف',
    'driver.pickUp': 'استلام',
    'driver.absent': 'غائب',
    'driver.lowFuelAlert': 'تنبيه انخفاض الوقود',
    'driver.trafficDelay': 'تأخير المرور',
    'driver.arrivedAtSchool': 'وصل إلى المدرسة',
    'driver.progress': 'التقدم',
    'driver.tracking': 'التتبع نشط',
    'driver.offline': 'غير متصل',
    'driver.routeTracking': 'تتبع المسار',
    'driver.liveLocation': 'الموقع المباشر',
    'driver.currentLocation': 'الموقع الحالي',
    'driver.studentList': 'قائمة الطلاب',
    'driver.report': 'تقرير',
    'driver.sendReport': 'إرسال تقرير',
    'driver.reportType': 'نوع التقرير',
    'driver.routeDelay': 'تأخير المسار',
    'driver.incidentReport': 'تقرير حادث',
    'driver.mechanicalIssue': 'مشكلة ميكانيكية',
    'driver.other': 'أخرى',
    'driver.message': 'الرسالة',
    'driver.describeIssue': 'صف المشكلة...',
    'driver.waiting': 'في الانتظار',
    'driver.pickedUp': 'تم الاستلام',
    'driver.droppedOff': 'تم التوصيل',
    'driver.busTracking': 'تتبع الحافلة',
    'driver.trackChildren': 'تتبع حافلة أطفالك في الوقت الفعلي',
    'driver.live': 'مباشر',
    'driver.minutes': 'دقيقة',
    
    // Transport
    'transport.manage': 'إدارة النقل المدرسي والحافلات',
    'transport.addBus': 'إضافة حافلة',
    'transport.totalBuses': 'إجمالي الحافلات',
    'transport.activeBuses': 'الحافلات النشطة',
    'transport.totalCapacity': 'السعة الإجمالية',
    'transport.currentStudents': 'الطلاب الحاليون',
    'transport.students': 'الطلاب',
    'transport.lastLocation': 'آخر موقع',
    'transport.updated': 'تحديث',
    'transport.route': 'المسار',
    'transport.editBus': 'تعديل معلومات الحافلة',
    'transport.driverName': 'اسم السائق',
    'transport.driverPhone': 'هاتف السائق',
    'transport.busNumber': 'رقم الحافلة',
    
    // Common
    'common.language': 'اللغة',
    'common.english': 'English',
    'common.arabic': 'العربية',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.actions': 'الإجراءات',
    'common.view': 'عرض',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.status': 'الحالة',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.pending': 'قيد الانتظار',
    'common.completed': 'مكتمل',
    'common.close': 'إغلاق',
    'common.currency': 'ر.ع',
    'common.name': 'الاسم',
    'common.nameAr': 'الاسم (بالعربية)',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.class': 'الفصل',
    'common.address': 'العنوان',
    'common.bloodGroup': 'فصيلة الدم',
    'common.allergies': 'الحساسية',
    'common.emergencyContact': 'اتصال الطوارئ',
    'common.dateOfBirth': 'تاريخ الميلاد',
    'common.parentName': 'اسم ولي الأمر',
    'common.parentPhone': 'هاتف ولي الأمر',
    'common.notes': 'ملاحظات',
    'common.importantNotes': 'ملاحظات مهمة',
    'common.contactInfo': 'معلومات الاتصال',
    'common.homeAddress': 'عنوان المنزل',
    'common.viewOnMap': 'عرض على الخريطة',
    'common.call': 'اتصال',
    'common.maintenance': 'صيانة',
    'common.capacity': 'السعة',
    'common.subject': 'المادة',
    'common.teacher': 'المعلم',
    'common.room': 'القاعة',
    'common.day': 'اليوم',
    'common.duration': 'المدة',
    'common.examType': 'نوع الامتحان',
    'common.newMessage': 'رسالة جديدة',
    'common.typeMessage': 'اكتب رسالتك...',
    'common.selectConversation': 'اختر محادثة للبدء في المراسلة',
    'common.messageSent': 'تم إرسال الرسالة',
    'common.messageSentDesc': 'تم إرسال رسالتك بنجاح',
    'common.searchConversations': 'البحث في المحادثات...',
    'common.calendar': 'التقويم',
    'common.deleted': 'حذف',
    'common.deletedDesc': 'تم حذف العنصر بنجاح',
    'common.savedSuccessfully': 'تم الحفظ بنجاح',
    'common.profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
    'common.welcomeDashboard': 'مرحباً بعودتك إلى لوحة إدارة المدرسة',
    'common.fromLastMonth': 'من الشهر الماضي',
    'common.recentActivities': 'الأنشطة الأخيرة',
    'common.upcomingEvents': 'الأحداث القادمة',
    'common.morningRoute': 'المسار الصباحي',
    'common.parentContact': 'اتصال ولي الأمر',
    'common.homeLocation': 'موقع المنزل',
    'common.openInMaps': 'فتح في الخرائط',
    'common.studentInfo': 'معلومات الطالب',
    'common.addClass': 'إضافة فصل',
    'common.classTeacher': 'معلم الفصل',
    'common.classesToday': 'الحصص اليوم',
    'common.classSchedule': 'جدول الحصص',
    'common.examSchedule': 'جدول الامتحانات',
    'common.addSchedule': 'إضافة جدول',
    'common.addExam': 'إضافة امتحان',
    'common.addClassSchedule': 'إضافة جدول حصة',
    'common.addExamSchedule': 'إضافة جدول امتحان',
    'common.emailCreated': 'تم إنشاء حساب البريد الإلكتروني',
    'common.emailCreatedDesc': 'تم إنشاء حساب البريد الإلكتروني بنجاح',
    'common.noPermission': 'ليس لديك إذن لعرض هذه الصفحة',
    'common.manageClasses': 'إدارة جداول الفصول والامتحانات',
    'common.communicateStaff': 'التواصل مع المعلمين وموظفي المدرسة',
    'common.driverDashboard': 'لوحة تحكم السائق',
    'common.busRouteManagement': 'إدارة مسار الحافلة وتتبع الطلاب',
    'common.teacherDashboard': 'لوحة تحكم المعلم',
    'common.manageYourClasses': 'إدارة فصولك وتتبع تقدم الطلاب',
    'common.barcode': 'الباركود',
    'common.nfcId': 'معرف NFC',
    'common.rollNumber': 'رقم الجلوس',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.approved': 'موافق عليه',
    'common.rejected': 'مرفوض',
    'common.available': 'متاح',
    'common.notAvailable': 'غير متاح',
    'common.id': 'المعرف',
    'common.grade': 'الصف',
    'common.section': 'القسم',
    'common.viewDetails': 'عرض التفاصيل',
    'common.noRecords': 'لا توجد سجلات',
    'common.noStudentsOnboard': 'لا يوجد طلاب على متن الحافلة',
    'common.noRecordsToday': 'لا توجد سجلات اليوم',
    
    // Footer
    'footer.allRightsReserved': 'جميع الحقوق محفوظة',
    
    // Log levels
    'log.info': 'معلومات',
    'log.warn': 'تحذير',
    'log.error': 'خطأ',
    'log.debug': 'تصحيح',
    
    // Status badges
    'status.draft': 'مسودة',
    'status.pendingApproval': 'في انتظار الموافقة',
    'status.approved': 'معتمد',
    'status.rejected': 'مرفوض',
    'status.active': 'نشط',
    'status.inactive': 'غير نشط',
    'status.available': 'متاح',
    'status.notAvailable': 'غير متاح',
    'status.present': 'حاضر',
    'status.absent': 'غائب',
    'status.late': 'متأخر',
    'status.notMarked': 'غير محدد',
    
    
    // Stats
    'stats.totalStudents': 'إجمالي الطلاب',
    'stats.totalTeachers': 'إجمالي المعلمين',
    'stats.attendance': 'معدل الحضور',
    'stats.busesActive': 'الحافلات النشطة',
    'stats.pendingFees': 'الرسوم المعلقة',
    
    // Features
    'feature.busTracking': 'تتبع الحافلة',
    'feature.wallet': 'المحفظة الرقمية',
    'feature.payments': 'المدفوعات',
    'feature.canteen': 'إدارة المقصف',
    
    // Schedule
    'schedule.mathematics': 'الرياضيات',
    'schedule.physics': 'الفيزياء',
    'schedule.english': 'اللغة الإنجليزية',
    'schedule.arabic': 'اللغة العربية',
    'schedule.chemistry': 'الكيمياء',
    'schedule.history': 'التاريخ',
    'schedule.pe': 'التربية الرياضية',
    'schedule.break': 'استراحة',
    'schedule.room': 'قاعة',
    'schedule.lab': 'مختبر',
    'schedule.canteen': 'المقصف',
    'schedule.sportsHall': 'الصالة الرياضية',
    'schedule.downloadSchedule': 'تنزيل الجدول',
    'schedule.todaySchedule': 'جدول اليوم',
    'schedule.scheduleSummary': 'ملخص الجدول',
    'schedule.classes': 'الحصص',
    'schedule.totalHours': 'إجمالي الساعات',
    'schedule.manageSchedules': 'عرض وإدارة الجداول اليومية',
    
    // Grades
    'grades.subject': 'المادة',
    'grades.grade': 'الدرجة',
    'grades.score': 'النتيجة',
    'grades.date': 'التاريخ',
    'grades.teacher': 'المعلم',
    'grades.exam': 'الامتحان',
    'grades.assignment': 'المهمة',
    'grades.project': 'المشروع',
    'grades.midterm': 'منتصف الفصل',
    'grades.final': 'نهائي',
    'grades.quiz': 'اختبار قصير',
    'grades.homework': 'واجب منزلي',
    'grades.classwork': 'عمل صفي',
    'grades.recentGrades': 'الدرجات الأخيرة',
    'grades.examType': 'نوع الامتحان',
    'grades.notes': 'ملاحظات',
    'grades.approve': 'اعتماد',
    'grades.addGrade': 'إضافة درجة',
    'grades.editGrade': 'تعديل درجة',
    'grades.selectClass': 'اختر الصف',
    'grades.selectStudent': 'اختر الطالب',
    'grades.selectSubject': 'اختر المادة',
    'grades.enterScore': 'أدخل الدرجة',
    'grades.enterNotes': 'أدخل الملاحظات',
    
    // Homework
    'homework.pendingHomework': 'الواجبات المعلقة',
    'homework.dueDate': 'تاريخ التسليم',
    'homework.submit': 'تسليم',
    'homework.submitted': 'تم التسليم',
    'homework.notSubmitted': 'لم يتم التسليم',
    
    // Exams
    'exams.upcomingExams': 'الامتحانات القادمة',
    'exams.examDate': 'تاريخ الامتحان',
    'exams.examTime': 'وقت الامتحان',
    'exams.examLocation': 'مكان الامتحان',
    
    // Time
    'time.minutes': 'دقائق',
    'time.hours': 'ساعات',
    'time.days': 'أيام',
    'time.ago': 'مضت',
    'time.min': 'دقيقة',
    'time.hrs': 'ساعة',
    
    // Student Profile
    'profile.studentWallet': 'محفظة الطالب',
    'profile.studentHomework': 'واجبات الطالب',
    'profile.studentNotes': 'الملاحظات',
    'profile.studentSchedules': 'الجداول',
    'profile.viewGrades': 'عرض الدرجات',
    'profile.manageWallet': 'إدارة المحفظة',
    
    // Payroll - Arabic translations
    'Employee ID': 'رقم الموظف',
    'Base Salary': 'الراتب الأساسي',
    'Configure': 'تكوين',
    'Payment Frequency': 'تكرار الدفع',
    'Teacher Payroll Configuration': 'تكوين رواتب المعلمين',
    'Teacher': 'المعلم',
    'Period': 'الفترة',
    'Net Salary': 'صافي الراتب',
    'Payment Date': 'تاريخ الدفع',
    'Process Payment': 'معالجة الدفع',
    'Configure Payroll': 'تكوين الرواتب',
    'Set up payroll configuration for': 'إعداد تكوين الرواتب لـ',
    'Base Salary (OMR)': 'الراتب الأساسي (ريال عماني)',
    'Hourly Rate (OMR) - Optional': 'الأجر بالساعة (ريال عماني) - اختياري',
    'Monthly': 'شهري',
    'Bi-Weekly': 'نصف شهري',
    'Weekly': 'أسبوعي',
    'Bank Account (Optional)': 'الحساب البنكي (اختياري)',
    'Saving...': 'جاري الحفظ...',
    'Calculate': 'حساب',
    'Calculate Salary': 'حساب الراتب',
    'Calculate salary for': 'حساب الراتب لـ',
    'Month': 'الشهر',
    'Year': 'السنة',
    'Calculating...': 'جاري الحساب...',
    'Process Salary Payment': 'معالجة دفع الراتب',
    'Confirm salary payment processing': 'تأكيد معالجة دفع الراتب',
    'Payment Confirmation': 'تأكيد الدفع',
    'You are about to transfer': 'أنت على وشك تحويل',
    'to': 'إلى',
    'Working Days': 'أيام العمل',
    'Present Days': 'أيام الحضور',
    'Deductions': 'الخصومات',
    'Bonuses': 'المكافآت',
    'Processing...': 'جاري المعالجة...',
    'Confirm Payment': 'تأكيد الدفع',
    'Payroll Records': 'سجلات الرواتب',
    'Teacher Attendance': 'حضور المعلمين',
    'Check In': 'تسجيل الدخول',
    'Check Out': 'تسجيل الخروج',
    'Total Hours': 'إجمالي الساعات',
    'Leave Requests': 'طلبات الإجازة',
    'Leave Type': 'نوع الإجازة',
    'Start Date': 'تاريخ البداية',
    'End Date': 'تاريخ النهاية',
    'Reason': 'السبب',
    'Vacation': 'إجازة',
    'Sick Leave': 'إجازة مرضية',
    'Personal': 'شخصي',
    'Emergency': 'طوارئ',
    'Request Leave': 'طلب إجازة',
    'Payroll Reports': 'تقارير الرواتب',
    'Generate Report': 'إنشاء تقرير',
    'Report Type': 'نوع التقرير',
    'Salary Summary': 'ملخص الرواتب',
    'Attendance Report': 'تقرير الحضور',
    'Deductions Report': 'تقرير الخصومات',
    'Select Period': 'اختر الفترة',
    'Current Month': 'الشهر الحالي',
    'Last Month': 'الشهر الماضي',
    'Custom Range': 'نطاق مخصص',
    'Download PDF': 'تحميل PDF',
    'Total Salaries': 'إجمالي الرواتب',
    'Total Deductions': 'إجمالي الخصومات',
    'Total Bonuses': 'إجمالي المكافآت',
    'Net Total': 'الإجمالي الصافي',
    'Payroll Overview': 'نظرة عامة على الرواتب',
    'Teachers Payroll': 'رواتب المعلمين',
    'Payroll Configuration': 'تكوين الرواتب',
    'Payment Status': 'حالة الدفع',
    'Paid': 'مدفوع',
    'Pending': 'معلق',
    'Approved': 'موافق عليه',
    'Rejected': 'مرفوض'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang) {
      setLanguageState(savedLang);
      document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = savedLang;
      document.documentElement.style.fontFamily = savedLang === 'ar' ? 
        'Cairo, sans-serif' : 'Inter, sans-serif';
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    document.documentElement.style.fontFamily = lang === 'ar' ? 
      'Cairo, sans-serif' : 'Inter, sans-serif';
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t,
      dir: language === 'ar' ? 'rtl' : 'ltr'
    }}>
      {children}
    </LanguageContext.Provider>
  );
};