import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations = {
  en: {
    // Auth
    'auth.selectRole': 'Select Your Role',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.welcomeBack': 'Welcome Back',
    'auth.loginSubtitle': 'Enter your credentials to access your account',
    
    // Roles
    'role.admin': 'Administrator',
    'role.teacher': 'Teacher',
    'role.parent': 'Parent',
    'role.student': 'Student',
    'role.driver': 'Driver',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Home Page',
    'dashboard.students': 'Students',
    'dashboard.teachers': 'Teachers',
    'dashboard.classes': 'Classes',
    'dashboard.attendance': 'Attendance',
    'dashboard.finance': 'Finance',
    'dashboard.transport': 'Transportation',
    'dashboard.canteen': 'Canteen',
    'dashboard.messages': 'Messages',
    'dashboard.settings': 'Settings',
    'dashboard.reports': 'Reports',
    'dashboard.schedule': 'Schedule',
    'dashboard.homework': 'Homework',
    'dashboard.grades': 'Grades',
    'dashboard.examSchedule': 'Exam Schedule',
    'dashboard.wallet': 'Wallet',
    'dashboard.kitchen': 'School Kitchen',
    'dashboard.tracking': 'Bus Tracking',
    'dashboard.profile': 'Profile',
    'dashboard.store': 'Store',
    'dashboard.feeManagement': 'Fee Management',
    'dashboard.parentFinance': 'Parent Finance',
    'dashboard.payroll': 'Payroll',
    'dashboard.userManagement': 'User Management',
    'dashboard.nfcManagement': 'NFC Management',
    
    // Parent Dashboard
    'parent.welcome': 'Welcome',
    'parent.monitorChildren': 'Monitor your children\'s academic progress and school activities',
    'parent.viewProfile': 'View Full Profile',
    'parent.trackBus': 'Track Bus',
    'parent.wallet': 'Wallet',
    'parent.payFees': 'Pay Fees',
    'parent.canteen': 'Canteen',
    'parent.todaySchedule': 'Today\'s Schedule',
    'parent.busStatus': 'Bus Status',
    'parent.feeStatus': 'Fee Status',
    'parent.morningPickup': 'Morning Pickup',
    'parent.afternoonDrop': 'Afternoon Drop',
    'parent.trackLive': 'Track Live',
    'parent.totalFees': 'Total Fees',
    'parent.paid': 'Paid',
    'parent.remaining': 'Remaining',
    'parent.payNow': 'Pay Now',
    'parent.attendance': 'Attendance',
    'parent.averageGrade': 'Average Grade',
    'parent.dailyAllowance': 'Daily Allowance',
    'parent.todaySpending': 'Today\'s Spending',
    'parent.grade': 'Grade',
    'parent.setHomeLocation': 'Set Home Location',
    'parent.store': 'School Store',
    
    // Students & Teachers
    'students.manageProfiles': 'Manage and view all student profiles',
    'students.searchPlaceholder': 'Search by name, NFC, or barcode...',
    'students.addStudent': 'Add Student',
    'students.viewFullProfile': 'View Full Profile',
    'students.editProfile': 'Edit Student Profile',
    'students.scanBarcode': 'Scan Barcode',
    'students.studentProfile': 'Student Profile',
    'students.readNFC': 'Read NFC',
    'students.readingNFC': 'Reading NFC Card...',
    'students.tapCard': 'Please tap the NFC card',
    'students.nfcSuccess': 'NFC Read Successful',
    'students.foundStudent': 'Found student',
    'teachers.manageProfiles': 'Manage and view all teacher profiles',
    'teachers.searchPlaceholder': 'Search by name or email...',
    'teachers.addTeacher': 'Add Teacher',
    'teachers.viewProfile': 'View Profile',
    'teachers.editProfile': 'Edit Teacher Profile',
    'teachers.createEmail': 'Create Email',
    'teachers.qualification': 'Qualification',
    'teachers.experience': 'Experience',
    'teachers.joinDate': 'Join Date',
    'teachers.subjects': 'Subjects',
    
    // Attendance
    'attendance.trackAttendance': 'Track student attendance in school and bus',
    'attendance.records': 'Attendance Records',
    'attendance.all': 'All',
    'attendance.school': 'School',
    'attendance.bus': 'Bus',
    'attendance.present': 'Present',
    'attendance.absent': 'Absent',
    'attendance.late': 'Late',
    'attendance.presentDays': 'Present Days',
    'attendance.absentDays': 'Absent Days',
    'attendance.lateDays': 'Late Days',
    'attendance.rate': 'Attendance Rate',
    'attendance.scanNFC': 'Scan NFC',
    'attendance.scanningNFC': 'Scanning NFC Card...',
    'attendance.tapStudent': 'Please tap the student card',
    'attendance.recorded': 'Attendance Recorded',
    'attendance.checkedIn': 'Student checked in successfully',
    
    // Driver specific
    'driver.dashboard': 'Driver Dashboard',
    'driver.route': 'Route',
    'driver.morningRoute': 'Morning Route',
    'driver.afternoonRoute': 'Afternoon Route',
    'driver.vehicle': 'Vehicle',
    'driver.students': 'Students',
    'driver.eta': 'ETA',
    'driver.toSchool': 'To school',
    'driver.nextStop': 'Next Stop',
    'driver.routeMap': 'Route Map',
    'driver.startNavigation': 'Start Navigation',
    'driver.studentPickupStatus': 'Student Pickup Status',
    'driver.quickActions': 'Quick Actions',
    'driver.markAbsent': 'Mark Student Absent',
    'driver.reportDelay': 'Report Delay',
    'driver.emergencyContact': 'Emergency Contact',
    'driver.endRoute': 'End Route',
    'driver.startRoute': 'Start Route',
    'driver.pauseRoute': 'Pause',
    'driver.resumeRoute': 'Resume',
    'driver.pickUp': 'Pick Up',
    'driver.absent': 'Absent',
    'driver.lowFuelAlert': 'Low Fuel Alert',
    'driver.trafficDelay': 'Traffic Delay',
    'driver.arrivedAtSchool': 'Arrived at School',
    'driver.progress': 'Progress',
    'driver.tracking': 'Tracking',
    'driver.offline': 'Offline',
    'driver.routeTracking': 'Route Tracking',
    'driver.liveLocation': 'Live Location',
    'driver.currentLocation': 'Current Location',
    'driver.studentList': 'Student List',
    'driver.report': 'Report',
    'driver.sendReport': 'Send Report',
    'driver.reportType': 'Report Type',
    'driver.routeDelay': 'Route Delay',
    'driver.incidentReport': 'Incident Report',
    'driver.mechanicalIssue': 'Mechanical Issue',
    'driver.other': 'Other',
    'driver.message': 'Message',
    'driver.describeIssue': 'Describe the issue...',
    'driver.waiting': 'Waiting',
    'driver.pickedUp': 'Picked Up',
    'driver.droppedOff': 'Dropped Off',
    
    // Transport
    'transport.manage': 'Manage school transportation and buses',
    'transport.addBus': 'Add Bus',
    'transport.totalBuses': 'Total Buses',
    'transport.activeBuses': 'Active Buses',
    'transport.totalCapacity': 'Total Capacity',
    'transport.currentStudents': 'Current Students',
    'transport.students': 'Students',
    'transport.lastLocation': 'Last Location',
    'transport.updated': 'Updated',
    'transport.route': 'Route',
    'transport.editBus': 'Edit Bus Information',
    'transport.driverName': 'Driver Name',
    'transport.driverPhone': 'Driver Phone',
    'transport.busNumber': 'Bus Number',
    
    // Common
    'common.language': 'Language',
    'common.english': 'English',
    'common.arabic': 'العربية',
    'common.hindi': 'हिन्दी',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.close': 'Close',
    'common.currency': 'OMR',
    'common.name': 'Name',
    'common.nameAr': 'Name (Arabic)',
    'common.nameHi': 'Name (Hindi)',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.class': 'Class',
    'common.address': 'Address',
    'common.bloodGroup': 'Blood Group',
    'common.allergies': 'Allergies',
    'common.emergencyContact': 'Emergency Contact',
    'common.dateOfBirth': 'Date of Birth',
    'common.parentName': 'Parent Name',
    'common.parentPhone': 'Parent Phone',
    'common.notes': 'Notes',
    'common.importantNotes': 'Important Notes',
    'common.contactInfo': 'Contact Information',
    'common.homeAddress': 'Home Address',
    'common.viewOnMap': 'View on Map',
    'common.call': 'Call',
    'common.maintenance': 'Maintenance',
    'common.capacity': 'Capacity',
    'common.subject': 'Subject',
    'common.teacher': 'Teacher',
    'common.room': 'Room',
    'common.day': 'Day',
    'common.duration': 'Duration',
    'common.examType': 'Exam Type',
    'common.newMessage': 'New Message',
    'common.typeMessage': 'Type your message...',
    'common.selectConversation': 'Select a conversation to start messaging',
    'common.messageSent': 'Message Sent',
    'common.messageSentDesc': 'Your message has been sent successfully',
    'common.searchConversations': 'Search conversations...',
    'common.calendar': 'Calendar',
    'common.deleted': 'Deleted',
    'common.deletedDesc': 'Item deleted successfully',
    'common.savedSuccessfully': 'Saved successfully',
    'common.profileUpdated': 'Profile updated successfully',
    'common.welcomeDashboard': 'Welcome back to your school management dashboard',
    'common.fromLastMonth': 'from last month',
    'common.recentActivities': 'Recent Activities',
    'common.upcomingEvents': 'Upcoming Events',
    'common.morningRoute': 'Morning Route',
    'common.parentContact': 'Parent Contact',
    'common.homeLocation': 'Home Location',
    'common.openInMaps': 'Open in Maps',
    'common.studentInfo': 'Student Information',
    'common.addClass': 'Add Class',
    'common.classTeacher': 'Class Teacher',
    'common.classesToday': 'Classes Today',
    'common.classSchedule': 'Class Schedule',
    'common.examSchedule': 'Exam Schedule',
    'common.addSchedule': 'Add Schedule',
    'common.addExam': 'Add Exam',
    'common.addClassSchedule': 'Add Class Schedule',
    'common.addExamSchedule': 'Add Exam Schedule',
    'common.emailCreated': 'Email Account Created',
    'common.emailCreatedDesc': 'Email account has been created successfully',
    'common.noPermission': 'You don\'t have permission to view this page',
    'common.manageClasses': 'Manage class schedules and exams',
    'common.communicateStaff': 'Communicate with teachers and school staff',
    'common.driverDashboard': 'Driver Dashboard',
    'common.busRouteManagement': 'Bus route management and student tracking',
    'common.teacherDashboard': 'Teacher Dashboard',
    'common.manageYourClasses': 'Manage your classes and track student progress',
    'common.barcode': 'Barcode',
    'common.nfcId': 'NFC ID',
    'common.rollNumber': 'Roll Number',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.available': 'Available',
    'common.notAvailable': 'Not Available',
    'common.id': 'ID',
    'common.grade': 'Grade',
    'common.section': 'Section',
    'common.viewDetails': 'View Details',
    'common.noRecords': 'No records found',
    'common.noStudentsOnboard': 'No students onboard',
    'common.noRecordsToday': 'No records yet today',
    
    // Footer
    'footer.allRightsReserved': 'All rights reserved',
    
    // Log levels
    'log.info': 'INFO',
    'log.warn': 'WARN', 
    'log.error': 'ERROR',
    'log.debug': 'DEBUG',
    
    // Status badges
    'status.draft': 'Draft',
    'status.pendingApproval': 'Pending Approval',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.available': 'Available',
    'status.notAvailable': 'Not Available',
    'status.present': 'Present',
    'status.absent': 'Absent',
    'status.late': 'Late',
    'status.notMarked': 'Not Marked',
    
    // Stats
    'stats.totalStudents': 'Total Students',
    'stats.totalTeachers': 'Total Teachers',
    'stats.attendance': 'Attendance Rate',
    'stats.busesActive': 'Active Buses',
    'stats.pendingFees': 'Pending Fees',
    
    // Features
    'feature.busTracking': 'Bus Tracking',
    'feature.wallet': 'Digital Wallet',
    'feature.payments': 'Payments',
    'feature.canteen': 'Canteen Management',
    
    // Schedule
    'schedule.mathematics': 'Mathematics',
    'schedule.physics': 'Physics',
    'schedule.english': 'English',
    'schedule.arabic': 'Arabic',
    'schedule.hindi': 'Hindi',
    'schedule.chemistry': 'Chemistry',
    'schedule.history': 'History',
    'schedule.pe': 'PE',
    'schedule.break': 'Break',
    'schedule.room': 'Room',
    'schedule.lab': 'Lab',
    'schedule.canteen': 'Canteen',
    'schedule.sportsHall': 'Sports Hall',
    'schedule.downloadSchedule': 'Download Schedule',
    'schedule.todaySchedule': "Today's Schedule",
    'schedule.scheduleSummary': 'Schedule Summary',
    'schedule.classes': 'Classes',
    'schedule.totalHours': 'Total Hours',
    'schedule.manageSchedules': 'View and manage daily schedules',
    
    // Grades
    'grades.subject': 'Subject',
    'grades.grade': 'Grade',
    'grades.score': 'Score',
    'grades.date': 'Date',
    'grades.teacher': 'Teacher',
    'grades.exam': 'Exam',
    'grades.assignment': 'Assignment',
    'grades.project': 'Project',
    'grades.midterm': 'Midterm',
    'grades.final': 'Final',
    'grades.quiz': 'Quiz',
    'grades.homework': 'Homework',
    'grades.classwork': 'Classwork',
    'grades.recentGrades': 'Recent Grades',
    'grades.examType': 'Exam Type',
    'grades.notes': 'Notes',
    'grades.approve': 'Approve',
    'grades.addGrade': 'Add Grade',
    'grades.editGrade': 'Edit Grade',
    'grades.selectClass': 'Select Class',
    'grades.selectStudent': 'Select Student',
    'grades.selectSubject': 'Select Subject',
    'grades.enterScore': 'Enter Score',
    'grades.enterNotes': 'Enter Notes',
    
    // Homework
    'homework.pendingHomework': 'Pending Homework',
    'homework.dueDate': 'Due Date',
    'homework.submit': 'Submit',
    'homework.submitted': 'Submitted',
    'homework.notSubmitted': 'Not Submitted',
    
    // Exams
    'exams.upcomingExams': 'Upcoming Exams',
    'exams.examDate': 'Exam Date',
    'exams.examTime': 'Exam Time',
    'exams.examLocation': 'Exam Location',
    
    // Time
    'time.minutes': 'minutes',
    'time.hours': 'hours',
    'time.days': 'days',
    'time.ago': 'ago',
    'time.min': 'min',
    'time.hrs': 'hrs',
    
    // Student Profile
    'profile.studentWallet': 'Student Wallet',
    'profile.studentHomework': 'Student Homework',
    'profile.studentNotes': 'Notes',
    'profile.studentSchedules': 'Schedules',
    'profile.viewGrades': 'View Grades',
    'profile.manageWallet': 'Manage Wallet',

    // Payroll
    'Employee ID': 'Employee ID',
    'Base Salary': 'Base Salary',
    'Configure': 'Configure',
    'Payment Frequency': 'Payment Frequency',
    'Teacher Payroll Configuration': 'Teacher Payroll Configuration',
    'Teacher': 'Teacher',
    'Period': 'Period',
    'Net Salary': 'Net Salary',
    'Payment Date': 'Payment Date',
    'Process Payment': 'Process Payment',
    'Configure Payroll': 'Configure Payroll',
    'Set up payroll configuration for': 'Set up payroll configuration for',
    'Base Salary (OMR)': 'Base Salary (OMR)',
    'Hourly Rate (OMR) - Optional': 'Hourly Rate (OMR) - Optional',
    'Monthly': 'Monthly',
    'Bi-Weekly': 'Bi-Weekly',
    'Weekly': 'Weekly',
    'Bank Account (Optional)': 'Bank Account (Optional)',
    'Saving...': 'Saving...',
    'Calculate': 'Calculate',
    'Calculate Salary': 'Calculate Salary',
    'Calculate salary for': 'Calculate salary for',
    'Month': 'Month',
    'Year': 'Year',
    'Calculating...': 'Calculating...',
    'Process Salary Payment': 'Process Salary Payment',
    'Confirm salary payment processing': 'Confirm salary payment processing',
    'Payment Confirmation': 'Payment Confirmation',
    'You are about to transfer': 'You are about to transfer',
    'to': 'to',
    'Working Days': 'Working Days',
    'Present Days': 'Present Days',
    'Deductions': 'Deductions',
    'Bonuses': 'Bonuses',
    'Processing...': 'Processing...',
    'Confirm Payment': 'Confirm Payment',
    'Payroll Records': 'Payroll Records',
    'Teacher Attendance': 'Teacher Attendance',
    'Check In': 'Check In',
    'Check Out': 'Check Out',
    'Total Hours': 'Total Hours',
    'Leave Requests': 'Leave Requests',
    'Leave Type': 'Leave Type',
    'Start Date': 'Start Date',
    'End Date': 'End Date',
    'Reason': 'Reason',
    'Vacation': 'Vacation',
    'Sick Leave': 'Sick Leave',
    'Personal': 'Personal',
    'Emergency': 'Emergency',
    'Request Leave': 'Request Leave',
    'Payroll Reports': 'Payroll Reports',
    'Generate Report': 'Generate Report',
    'Report Type': 'Report Type',
    'Salary Summary': 'Salary Summary',
    'Attendance Report': 'Attendance Report',
    'Deductions Report': 'Deductions Report',
    'Select Period': 'Select Period',
    'Current Month': 'Current Month',
    'Last Month': 'Last Month',
    'Custom Range': 'Custom Range',
    'Download PDF': 'Download PDF',
    'Total Salaries': 'Total Salaries',
    'Total Deductions': 'Total Deductions',
    'Total Bonuses': 'Total Bonuses',
    'Net Total': 'Net Total',
    'Payroll Overview': 'Payroll Overview',
    'Teachers Payroll': 'Teachers Payroll',
    'Payroll Configuration': 'Payroll Configuration',
    'Payment Status': 'Payment Status',
    'Paid': 'Paid',
    'Pending': 'Pending',
    'Approved': 'Approved',
    'Rejected': 'Rejected',

    // Network Status
    'network.connected': 'Connected to internet',
    'network.disconnected': 'No internet connection',
    'network.backOnline': 'You are back online',
    'network.offline': 'You are offline',
  },
  ar: {
    // Auth
    'auth.selectRole': 'اختر دورك',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.loginSubtitle': 'أدخل بيانات الاعتماد الخاصة بك للوصول إلى حسابك',
    
    // Roles
    'role.admin': 'المدير',
    'role.teacher': 'المعلم',
    'role.parent': 'ولي الأمر',
    'role.student': 'الطالب',
    'role.driver': 'السائق',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.overview': 'الصفحة الرئيسية',
    'dashboard.students': 'الطلاب',
    'dashboard.teachers': 'المعلمون',
    'dashboard.classes': 'الفصول',
    'dashboard.attendance': 'الحضور',
    'dashboard.finance': 'المالية',
    'dashboard.transport': 'النقل',
    'dashboard.canteen': 'المقصف',
    'dashboard.messages': 'الرسائل',
    'dashboard.settings': 'الإعدادات',
    'dashboard.reports': 'التقارير',
    'dashboard.schedule': 'الجدول',
    'dashboard.homework': 'الواجبات',
    'dashboard.grades': 'الدرجات',
    'dashboard.examSchedule': 'جدول الامتحانات',
    'dashboard.wallet': 'المحفظة',
    'dashboard.kitchen': 'مطبخ المدرسة',
    'dashboard.tracking': 'تتبع الحافلة',
    'dashboard.profile': 'الملف الشخصي',
    'dashboard.store': 'المتجر',
    'dashboard.feeManagement': 'إدارة الرسوم',
    'dashboard.parentFinance': 'المالية للوالدين',
    'dashboard.payroll': 'الرواتب',
    'dashboard.userManagement': 'إدارة المستخدمين',
    'dashboard.nfcManagement': 'إدارة NFC',
    
    // Parent Dashboard
    'parent.welcome': 'مرحباً',
    'parent.monitorChildren': 'راقب التقدم الأكاديمي لأطفالك والأنشطة المدرسية',
    'parent.viewProfile': 'عرض الملف الكامل',
    'parent.trackBus': 'تتبع الحافلة',
    'parent.wallet': 'المحفظة',
    'parent.payFees': 'دفع الرسوم',
    'parent.canteen': 'المقصف',
    'parent.todaySchedule': 'جدول اليوم',
    'parent.busStatus': 'حالة الحافلة',
    'parent.feeStatus': 'حالة الرسوم',
    'parent.morningPickup': 'الاستلام الصباحي',
    'parent.afternoonDrop': 'التوصيل بعد الظهر',
    'parent.trackLive': 'تتبع مباشر',
    'parent.totalFees': 'إجمالي الرسوم',
    'parent.paid': 'مدفوع',
    'parent.remaining': 'متبقي',
    'parent.payNow': 'ادفع الآن',
    'parent.attendance': 'الحضور',
    'parent.averageGrade': 'متوسط الدرجة',
    'parent.dailyAllowance': 'المصروف اليومي',
    'parent.todaySpending': 'مصروف اليوم',
    'parent.grade': 'الصف',
    'parent.setHomeLocation': 'تحديد موقع المنزل',
    'parent.store': 'المتجر المدرسي',
    
    // Students & Teachers
    'students.manageProfiles': 'إدارة وعرض جميع ملفات الطلاب',
    'students.searchPlaceholder': 'البحث بالاسم أو NFC أو الباركود...',
    'students.addStudent': 'إضافة طالب',
    'students.viewFullProfile': 'عرض الملف الكامل',
    'students.editProfile': 'تعديل ملف الطالب',
    'students.scanBarcode': 'مسح الباركود',
    'students.studentProfile': 'ملف الطالب',
    'students.readNFC': 'قراءة NFC',
    'students.readingNFC': 'قراءة بطاقة NFC...',
    'students.tapCard': 'يرجى تقريب بطاقة NFC',
    'students.nfcSuccess': 'تمت قراءة NFC بنجاح',
    'students.foundStudent': 'تم العثور على الطالب',
    'teachers.manageProfiles': 'إدارة وعرض جميع ملفات المعلمين',
    'teachers.searchPlaceholder': 'البحث بالاسم أو البريد الإلكتروني...',
    'teachers.addTeacher': 'إضافة معلم',
    'teachers.viewProfile': 'عرض الملف',
    'teachers.editProfile': 'تعديل ملف المعلم',
    'teachers.createEmail': 'إنشاء بريد',
    'teachers.qualification': 'المؤهل',
    'teachers.experience': 'الخبرة',
    'teachers.joinDate': 'تاريخ الانضمام',
    'teachers.subjects': 'المواد',
    
    // Attendance
    'attendance.trackAttendance': 'تتبع حضور الطلاب في المدرسة والحافلة',
    'attendance.records': 'سجلات الحضور',
    'attendance.all': 'الكل',
    'attendance.school': 'المدرسة',
    'attendance.bus': 'الحافلة',
    'attendance.present': 'حاضر',
    'attendance.absent': 'غائب',
    'attendance.late': 'متأخر',
    'attendance.presentDays': 'أيام الحضور',
    'attendance.absentDays': 'أيام الغياب',
    'attendance.lateDays': 'أيام التأخير',
    'attendance.rate': 'معدل الحضور',
    'attendance.scanNFC': 'مسح NFC',
    'attendance.scanningNFC': 'مسح بطاقة NFC...',
    'attendance.tapStudent': 'يرجى تقريب بطاقة الطالب',
    'attendance.recorded': 'تم تسجيل الحضور',
    'attendance.checkedIn': 'تم تسجيل حضور الطالب بنجاح',
    
    // Driver specific
    'driver.dashboard': 'لوحة تحكم السائق',
    'driver.route': 'المسار',
    'driver.morningRoute': 'الرحلة الصباحية',
    'driver.afternoonRoute': 'رحلة بعد الظهر',
    'driver.vehicle': 'المركبة',
    'driver.students': 'الطلاب',
    'driver.eta': 'الوقت المتوقع للوصول',
    'driver.toSchool': 'إلى المدرسة',
    'driver.nextStop': 'المحطة التالية',
    'driver.routeMap': 'خريطة المسار',
    'driver.startNavigation': 'بدء الملاحة',
    'driver.studentPickupStatus': 'حالة استلام الطلاب',
    'driver.quickActions': 'الإجراءات السريعة',
    'driver.markAbsent': 'تسجيل غياب طالب',
    'driver.reportDelay': 'الإبلاغ عن تأخير',
    'driver.emergencyContact': 'الاتصال الطارئ',
    'driver.endRoute': 'إنهاء الرحلة',
    'driver.startRoute': 'بدء المسار',
    'driver.pauseRoute': 'إيقاف مؤقت',
    'driver.resumeRoute': 'استئناف',
    'driver.pickUp': 'استلام',
    'driver.absent': 'غائب',
    'driver.lowFuelAlert': 'تنبيه انخفاض الوقود',
    'driver.trafficDelay': 'تأخير المرور',
    'driver.arrivedAtSchool': 'وصل إلى المدرسة',
    'driver.progress': 'التقدم',
    'driver.tracking': 'التتبع نشط',
    'driver.offline': 'غير متصل',
    'driver.routeTracking': 'تتبع المسار',
    'driver.liveLocation': 'الموقع المباشر',
    'driver.currentLocation': 'الموقع الحالي',
    'driver.studentList': 'قائمة الطلاب',
    'driver.report': 'تقرير',
    'driver.sendReport': 'إرسال تقرير',
    'driver.reportType': 'نوع التقرير',
    'driver.routeDelay': 'تأخير المسار',
    'driver.incidentReport': 'تقرير حادث',
    'driver.mechanicalIssue': 'مشكلة ميكانيكية',
    'driver.other': 'أخرى',
    'driver.message': 'الرسالة',
    'driver.describeIssue': 'صف المشكلة...',
    'driver.waiting': 'في الانتظار',
    'driver.pickedUp': 'تم الاستلام',
    'driver.droppedOff': 'تم التوصيل',
    'driver.busTracking': 'تتبع الحافلة',
    'driver.trackChildren': 'تتبع حافلة أطفالك في الوقت الفعلي',
    'driver.live': 'مباشر',
    'driver.minutes': 'دقيقة',
    
    // Transport
    'transport.manage': 'إدارة النقل المدرسي والحافلات',
    'transport.addBus': 'إضافة حافلة',
    'transport.totalBuses': 'إجمالي الحافلات',
    'transport.activeBuses': 'الحافلات النشطة',
    'transport.totalCapacity': 'السعة الإجمالية',
    'transport.currentStudents': 'الطلاب الحاليون',
    'transport.students': 'الطلاب',
    'transport.lastLocation': 'آخر موقع',
    'transport.updated': 'تحديث',
    'transport.route': 'المسار',
    'transport.editBus': 'تعديل معلومات الحافلة',
    'transport.driverName': 'اسم السائق',
    'transport.driverPhone': 'هاتف السائق',
    'transport.busNumber': 'رقم الحافلة',
    
    // Common
    'common.language': 'اللغة',
    'common.english': 'English',
    'common.arabic': 'العربية',
    'common.hindi': 'हिन्दी',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.actions': 'الإجراءات',
    'common.view': 'عرض',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.status': 'الحالة',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.pending': 'قيد الانتظار',
    'common.completed': 'مكتمل',
    'common.close': 'إغلاق',
    'common.currency': 'ر.ع',
    'common.name': 'الاسم',
    'common.nameAr': 'الاسم (بالعربية)',
    'common.nameHi': 'الاسم (بالهندية)',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.class': 'الفصل',
    'common.address': 'العنوان',
    'common.bloodGroup': 'فصيلة الدم',
    'common.allergies': 'الحساسية',
    'common.emergencyContact': 'اتصال الطوارئ',
    'common.dateOfBirth': 'تاريخ الميلاد',
    'common.parentName': 'اسم ولي الأمر',
    'common.parentPhone': 'هاتف ولي الأمر',
    'common.notes': 'ملاحظات',
    'common.importantNotes': 'ملاحظات مهمة',
    'common.contactInfo': 'معلومات الاتصال',
    'common.homeAddress': 'عنوان المنزل',
    'common.viewOnMap': 'عرض على الخريطة',
    'common.call': 'اتصال',
    'common.maintenance': 'صيانة',
    'common.capacity': 'السعة',
    'common.subject': 'المادة',
    'common.teacher': 'المعلم',
    'common.room': 'القاعة',
    'common.day': 'اليوم',
    'common.duration': 'المدة',
    'common.examType': 'نوع الامتحان',
    'common.newMessage': 'رسالة جديدة',
    'common.typeMessage': 'اكتب رسالتك...',
    'common.selectConversation': 'اختر محادثة للبدء في المراسلة',
    'common.messageSent': 'تم إرسال الرسالة',
    'common.messageSentDesc': 'تم إرسال رسالتك بنجاح',
    'common.searchConversations': 'البحث في المحادثات...',
    'common.calendar': 'التقويم',
    'common.deleted': 'حذف',
    'common.deletedDesc': 'تم حذف العنصر بنجاح',
    'common.savedSuccessfully': 'تم الحفظ بنجاح',
    'common.profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
    'common.welcomeDashboard': 'مرحباً بعودتك إلى لوحة إدارة المدرسة',
    'common.fromLastMonth': 'من الشهر الماضي',
    'common.recentActivities': 'الأنشطة الأخيرة',
    'common.upcomingEvents': 'الأحداث القادمة',
    'common.morningRoute': 'المسار الصباحي',
    'common.parentContact': 'اتصال ولي الأمر',
    'common.homeLocation': 'موقع المنزل',
    'common.openInMaps': 'فتح في الخرائط',
    'common.studentInfo': 'معلومات الطالب',
    'common.addClass': 'إضافة فصل',
    'common.classTeacher': 'معلم الفصل',
    'common.classesToday': 'الحصص اليوم',
    'common.classSchedule': 'جدول الحصص',
    'common.examSchedule': 'جدول الامتحانات',
    'common.addSchedule': 'إضافة جدول',
    'common.addExam': 'إضافة امتحان',
    'common.addClassSchedule': 'إضافة جدول حصة',
    'common.addExamSchedule': 'إضافة جدول امتحان',
    'common.emailCreated': 'تم إنشاء حساب البريد الإلكتروني',
    'common.emailCreatedDesc': 'تم إنشاء حساب البريد الإلكتروني بنجاح',
    'common.noPermission': 'ليس لديك إذن لعرض هذه الصفحة',
    'common.manageClasses': 'إدارة جداول الفصول والامتحانات',
    'common.communicateStaff': 'التواصل مع المعلمين وموظفي المدرسة',
    'common.driverDashboard': 'لوحة تحكم السائق',
    'common.busRouteManagement': 'إدارة مسار الحافلة وتتبع الطلاب',
    'common.teacherDashboard': 'لوحة تحكم المعلم',
    'common.manageYourClasses': 'إدارة فصولك وتتبع تقدم الطلاب',
    'common.barcode': 'الباركود',
    'common.nfcId': 'معرف NFC',
    'common.rollNumber': 'رقم الجلوس',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.approved': 'موافق عليه',
    'common.rejected': 'مرفوض',
    'common.available': 'متاح',
    'common.notAvailable': 'غير متاح',
    'common.id': 'المعرف',
    'common.grade': 'الصف',
    'common.section': 'القسم',
    'common.viewDetails': 'عرض التفاصيل',
    'common.noRecords': 'لا توجد سجلات',
    'common.noStudentsOnboard': 'لا يوجد طلاب على متن الحافلة',
    'common.noRecordsToday': 'لا توجد سجلات اليوم',
    
    // Footer
    'footer.allRightsReserved': 'جميع الحقوق محفوظة',
    
    // Log levels
    'log.info': 'معلومات',
    'log.warn': 'تحذير',
    'log.error': 'خطأ',
    'log.debug': 'تصحيح',
    
    // Status badges
    'status.draft': 'مسودة',
    'status.pendingApproval': 'في انتظار الموافقة',
    'status.approved': 'معتمد',
    'status.rejected': 'مرفوض',
    'status.active': 'نشط',
    'status.inactive': 'غير نشط',
    'status.available': 'متاح',
    'status.notAvailable': 'غير متاح',
    'status.present': 'حاضر',
    'status.absent': 'غائب',
    'status.late': 'متأخر',
    'status.notMarked': 'غير محدد',
    
    
    // Stats
    'stats.totalStudents': 'إجمالي الطلاب',
    'stats.totalTeachers': 'إجمالي المعلمين',
    'stats.attendance': 'معدل الحضور',
    'stats.busesActive': 'الحافلات النشطة',
    'stats.pendingFees': 'الرسوم المعلقة',
    
    // Features
    'feature.busTracking': 'تتبع الحافلة',
    'feature.wallet': 'المحفظة الرقمية',
    'feature.payments': 'المدفوعات',
    'feature.canteen': 'إدارة المقصف',
    
    // Schedule
    'schedule.mathematics': 'الرياضيات',
    'schedule.physics': 'الفيزياء',
    'schedule.english': 'اللغة الإنجليزية',
    'schedule.arabic': 'اللغة العربية',
    'schedule.hindi': 'اللغة الهندية',
    'schedule.chemistry': 'الكيمياء',
    'schedule.history': 'التاريخ',
    'schedule.pe': 'التربية الرياضية',
    'schedule.break': 'استراحة',
    'schedule.room': 'قاعة',
    'schedule.lab': 'مختبر',
    'schedule.canteen': 'المقصف',
    'schedule.sportsHall': 'الصالة الرياضية',
    'schedule.downloadSchedule': 'تنزيل الجدول',
    'schedule.todaySchedule': 'جدول اليوم',
    'schedule.scheduleSummary': 'ملخص الجدول',
    'schedule.classes': 'الحصص',
    'schedule.totalHours': 'إجمالي الساعات',
    'schedule.manageSchedules': 'عرض وإدارة الجداول اليومية',
    
    // Grades
    'grades.subject': 'المادة',
    'grades.grade': 'الدرجة',
    'grades.score': 'النتيجة',
    'grades.date': 'التاريخ',
    'grades.teacher': 'المعلم',
    'grades.exam': 'الامتحان',
    'grades.assignment': 'المهمة',
    'grades.project': 'المشروع',
    'grades.midterm': 'منتصف الفصل',
    'grades.final': 'نهائي',
    'grades.quiz': 'اختبار قصير',
    'grades.homework': 'واجب منزلي',
    'grades.classwork': 'عمل صفي',
    'grades.recentGrades': 'الدرجات الأخيرة',
    'grades.examType': 'نوع الامتحان',
    'grades.notes': 'ملاحظات',
    'grades.approve': 'اعتماد',
    'grades.addGrade': 'إضافة درجة',
    'grades.editGrade': 'تعديل درجة',
    'grades.selectClass': 'اختر الصف',
    'grades.selectStudent': 'اختر الطالب',
    'grades.selectSubject': 'اختر المادة',
    'grades.enterScore': 'أدخل الدرجة',
    'grades.enterNotes': 'أدخل الملاحظات',
    
    // Homework
    'homework.pendingHomework': 'الواجبات المعلقة',
    'homework.dueDate': 'تاريخ التسليم',
    'homework.submit': 'تسليم',
    'homework.submitted': 'تم التسليم',
    'homework.notSubmitted': 'لم يتم التسليم',
    
    // Exams
    'exams.upcomingExams': 'الامتحانات القادمة',
    'exams.examDate': 'تاريخ الامتحان',
    'exams.examTime': 'وقت الامتحان',
    'exams.examLocation': 'مكان الامتحان',
    
    // Time
    'time.minutes': 'دقائق',
    'time.hours': 'ساعات',
    'time.days': 'أيام',
    'time.ago': 'مضت',
    'time.min': 'دقيقة',
    'time.hrs': 'ساعة',
    
    // Student Profile
    'profile.studentWallet': 'محفظة الطالب',
    'profile.studentHomework': 'واجبات الطالب',
    'profile.studentNotes': 'الملاحظات',
    'profile.studentSchedules': 'الجداول',
    'profile.viewGrades': 'عرض الدرجات',
    'profile.manageWallet': 'إدارة المحفظة',
    
    // Payroll - Arabic translations
    'Employee ID': 'رقم الموظف',
    'Base Salary': 'الراتب الأساسي',
    'Configure': 'تكوين',
    'Payment Frequency': 'تكرار الدفع',
    'Teacher Payroll Configuration': 'تكوين رواتب المعلمين',
    'Teacher': 'المعلم',
    'Period': 'الفترة',
    'Net Salary': 'صافي الراتب',
    'Payment Date': 'تاريخ الدفع',
    'Process Payment': 'معالجة الدفع',
    'Configure Payroll': 'تكوين الرواتب',
    'Set up payroll configuration for': 'إعداد تكوين الرواتب لـ',
    'Base Salary (OMR)': 'الراتب الأساسي (ريال عماني)',
    'Hourly Rate (OMR) - Optional': 'الأجر بالساعة (ريال عماني) - اختياري',
    'Monthly': 'شهري',
    'Bi-Weekly': 'نصف شهري',
    'Weekly': 'أسبوعي',
    'Bank Account (Optional)': 'الحساب البنكي (اختياري)',
    'Saving...': 'جاري الحفظ...',
    'Calculate': 'حساب',
    'Calculate Salary': 'حساب الراتب',
    'Calculate salary for': 'حساب الراتب لـ',
    'Month': 'الشهر',
    'Year': 'السنة',
    'Calculating...': 'جاري الحساب...',
    'Process Salary Payment': 'معالجة دفع الراتب',
    'Confirm salary payment processing': 'تأكيد معالجة دفع الراتب',
    'Payment Confirmation': 'تأكيد الدفع',
    'You are about to transfer': 'أنت على وشك تحويل',
    'to': 'إلى',
    'Working Days': 'أيام العمل',
    'Present Days': 'أيام الحضور',
    'Deductions': 'الخصومات',
    'Bonuses': 'المكافآت',
    'Processing...': 'جاري المعالجة...',
    'Confirm Payment': 'تأكيد الدفع',
    'Payroll Records': 'سجلات الرواتب',
    'Teacher Attendance': 'حضور المعلمين',
    'Check In': 'تسجيل الدخول',
    'Check Out': 'تسجيل الخروج',
    'Total Hours': 'إجمالي الساعات',
    'Leave Requests': 'طلبات الإجازة',
    'Leave Type': 'نوع الإجازة',
    'Start Date': 'تاريخ البداية',
    'End Date': 'تاريخ النهاية',
    'Reason': 'السبب',
    'Vacation': 'إجازة',
    'Sick Leave': 'إجازة مرضية',
    'Personal': 'شخصي',
    'Emergency': 'طوارئ',
    'Request Leave': 'طلب إجازة',
    'Payroll Reports': 'تقارير الرواتب',
    'Generate Report': 'إنشاء تقرير',
    'Report Type': 'نوع التقرير',
    'Salary Summary': 'ملخص الرواتب',
    'Attendance Report': 'تقرير الحضور',
    'Deductions Report': 'تقرير الخصومات',
    'Select Period': 'اختر الفترة',
    'Current Month': 'الشهر الحالي',
    'Last Month': 'الشهر الماضي',
    'Custom Range': 'نطاق مخصص',
    'Download PDF': 'تحميل PDF',
    'Total Salaries': 'إجمالي الرواتب',
    'Total Deductions': 'إجمالي الخصومات',
    'Total Bonuses': 'إجمالي المكافآت',
    'Net Total': 'الإجمالي الصافي',
    'Payroll Overview': 'نظرة عامة على الرواتب',
    'Teachers Payroll': 'رواتب المعلمين',
    'Payroll Configuration': 'تكوين الرواتب',
    'Payment Status': 'حالة الدفع',
    'Paid': 'مدفوع',
    'Pending': 'معلق',
    'Approved': 'موافق عليه',
    'Rejected': 'مرفوض',

    // Network Status
    'network.connected': 'متصل بالإنترنت',
    'network.disconnected': 'لا يوجد اتصال بالإنترنت',
    'network.backOnline': 'أنت متصل مرة أخرى',
    'network.offline': 'أنت غير متصل',
  },
  hi: {
    // Auth
    'auth.selectRole': 'अपनी भूमिका चुनें',
    'auth.login': 'लॉग इन करें',
    'auth.logout': 'लॉग आउट करें',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.welcomeBack': 'पुनः स्वागत है',
    'auth.loginSubtitle': 'अपने खाते तक पहुँचने के लिए अपने क्रेडेंशियल दर्ज करें',
    
    // Roles
    'role.admin': 'प्रशासक',
    'role.teacher': 'शिक्षक',
    'role.parent': 'अभिभावक',
    'role.student': 'छात्र',
    'role.driver': 'चालक',
    
    // Dashboard
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.overview': 'होम पेज',
    'dashboard.students': 'छात्र',
    'dashboard.teachers': 'शिक्षक',
    'dashboard.classes': 'कक्षाएँ',
    'dashboard.attendance': 'उपस्थिति',
    'dashboard.finance': 'वित्त',
    'dashboard.transport': 'परिवहन',
    'dashboard.canteen': 'कैंटीन',
    'dashboard.messages': 'संदेश',
    'dashboard.settings': 'सेटिंग्स',
    'dashboard.reports': 'रिपोर्ट',
    'dashboard.schedule': 'समय सारणी',
    'dashboard.homework': 'गृहकार्य',
    'dashboard.grades': 'अंक',
    'dashboard.examSchedule': 'परीक्षा समय सारणी',
    'dashboard.wallet': 'वॉलेट',
    'dashboard.kitchen': 'स्कूल किचन',
    'dashboard.tracking': 'बस ट्रैकिंग',
    'dashboard.profile': 'प्रोफ़ाइल',
    'dashboard.store': 'स्टोर',
    'dashboard.feeManagement': 'शुल्क प्रबंधन',
    'dashboard.parentFinance': 'अभिभावक वित्त',
    'dashboard.payroll': 'वेतन',
    'dashboard.userManagement': 'उपयोगकर्ता प्रबंधन',
    'dashboard.nfcManagement': 'NFC प्रबंधन',
    
    // Parent Dashboard
    'parent.welcome': 'स्वागत है',
    'parent.monitorChildren': 'अपने बच्चों की शैक्षणिक प्रगति और स्कूल गतिविधियों की निगरानी करें',
    'parent.viewProfile': 'पूर्ण प्रोफ़ाइल देखें',
    'parent.trackBus': 'बस ट्रैक करें',
    'parent.wallet': 'वॉलेट',
    'parent.payFees': 'शुल्क भुगतान',
    'parent.canteen': 'कैंटीन',
    'parent.todaySchedule': 'आज की समय सारणी',
    'parent.busStatus': 'बस स्थिति',
    'parent.feeStatus': 'शुल्क स्थिति',
    'parent.morningPickup': 'सुबह की पिकअप',
    'parent.afternoonDrop': 'दोपहर की ड्रॉप',
    'parent.trackLive': 'लाइव ट्रैक करें',
    'parent.totalFees': 'कुल शुल्क',
    'parent.paid': 'भुगतान किया',
    'parent.remaining': 'शेष',
    'parent.payNow': 'अभी भुगतान करें',
    'parent.attendance': 'उपस्थिति',
    'parent.averageGrade': 'औसत अंक',
    'parent.dailyAllowance': 'दैनिक भत्ता',
    'parent.todaySpending': 'आज का खर्च',
    'parent.grade': 'कक्षा',
    'parent.setHomeLocation': 'घर का स्थान सेट करें',
    'parent.store': 'स्कूल स्टोर',
    
    // Students & Teachers
    'students.manageProfiles': 'सभी छात्र प्रोफ़ाइल प्रबंधित करें और देखें',
    'students.searchPlaceholder': 'नाम, NFC, या बारकोड से खोजें...',
    'students.addStudent': 'छात्र जोड़ें',
    'students.viewFullProfile': 'पूर्ण प्रोफ़ाइल देखें',
    'students.editProfile': 'छात्र प्रोफ़ाइल संपादित करें',
    'students.scanBarcode': 'बारकोड स्कैन करें',
    'students.studentProfile': 'छात्र प्रोफ़ाइल',
    'students.readNFC': 'NFC पढ़ें',
    'students.readingNFC': 'NFC कार्ड पढ़ रहे हैं...',
    'students.tapCard': 'कृपया NFC कार्ड टैप करें',
    'students.nfcSuccess': 'NFC सफलतापूर्वक पढ़ा गया',
    'students.foundStudent': 'छात्र मिला',
    'teachers.manageProfiles': 'सभी शिक्षक प्रोफ़ाइल प्रबंधित करें और देखें',
    'teachers.searchPlaceholder': 'नाम या ईमेल से खोजें...',
    'teachers.addTeacher': 'शिक्षक जोड़ें',
    'teachers.viewProfile': 'प्रोफ़ाइल देखें',
    'teachers.editProfile': 'शिक्षक प्रोफ़ाइल संपादित करें',
    'teachers.createEmail': 'ईमेल बनाएं',
    'teachers.qualification': 'योग्यता',
    'teachers.experience': 'अनुभव',
    'teachers.joinDate': 'जॉइनिंग तिथि',
    'teachers.subjects': 'विषय',
    
    // Attendance
    'attendance.trackAttendance': 'स्कूल और बस में छात्र उपस्थिति ट्रैक करें',
    'attendance.records': 'उपस्थिति रिकॉर्ड',
    'attendance.all': 'सभी',
    'attendance.school': 'स्कूल',
    'attendance.bus': 'बस',
    'attendance.present': 'उपस्थित',
    'attendance.absent': 'अनुपस्थित',
    'attendance.late': 'देर से',
    'attendance.presentDays': 'उपस्थिति के दिन',
    'attendance.absentDays': 'अनुपस्थिति के दिन',
    'attendance.lateDays': 'देरी के दिन',
    'attendance.rate': 'उपस्थिति दर',
    'attendance.scanNFC': 'NFC स्कैन करें',
    'attendance.scanningNFC': 'NFC कार्ड स्कैन कर रहे हैं...',
    'attendance.tapStudent': 'कृपया छात्र का कार्ड टैप करें',
    'attendance.recorded': 'उपस्थिति दर्ज',
    'attendance.checkedIn': 'छात्र सफलतापूर्वक चेक-इन हो गया',
    
    // Driver specific
    'driver.dashboard': 'ड्राइवर डैशबोर्ड',
    'driver.route': 'मार्ग',
    'driver.morningRoute': 'सुबह का मार्ग',
    'driver.afternoonRoute': 'दोपहर का मार्ग',
    'driver.vehicle': 'वाहन',
    'driver.students': 'छात्र',
    'driver.eta': 'पहुँचने का अनुमानित समय',
    'driver.toSchool': 'स्कूल के लिए',
    'driver.nextStop': 'अगला स्टॉप',
    'driver.routeMap': 'मार्ग मानचित्र',
    'driver.startNavigation': 'नेविगेशन शुरू करें',
    'driver.studentPickupStatus': 'छात्र पिकअप स्थिति',
    'driver.quickActions': 'त्वरित कार्य',
    'driver.markAbsent': 'छात्र को अनुपस्थित चिह्नित करें',
    'driver.reportDelay': 'देरी की रिपोर्ट करें',
    'driver.emergencyContact': 'आपातकालीन संपर्क',
    'driver.endRoute': 'मार्ग समाप्त करें',
    'driver.startRoute': 'मार्ग शुरू करें',
    'driver.pauseRoute': 'रोकें',
    'driver.resumeRoute': 'जारी रखें',
    'driver.pickUp': 'पिक अप',
    'driver.absent': 'अनुपस्थित',
    'driver.lowFuelAlert': 'कम ईंधन अलर्ट',
    'driver.trafficDelay': 'ट्रैफ़िक देरी',
    'driver.arrivedAtSchool': 'स्कूल पहुँच गए',
    'driver.progress': 'प्रगति',
    'driver.tracking': 'ट्रैकिंग',
    'driver.offline': 'ऑफ़लाइन',
    'driver.routeTracking': 'मार्ग ट्रैकिंग',
    'driver.liveLocation': 'लाइव लोकेशन',
    'driver.currentLocation': 'वर्तमान स्थान',
    'driver.studentList': 'छात्र सूची',
    'driver.report': 'रिपोर्ट',
    'driver.sendReport': 'रिपोर्ट भेजें',
    'driver.reportType': 'रिपोर्ट प्रकार',
    'driver.routeDelay': 'मार्ग देरी',
    'driver.incidentReport': 'घटना रिपोर्ट',
    'driver.mechanicalIssue': 'यांत्रिक समस्या',
    'driver.other': 'अन्य',
    'driver.message': 'संदेश',
    'driver.describeIssue': 'समस्या का वर्णन करें...',
    'driver.waiting': 'प्रतीक्षा में',
    'driver.pickedUp': 'उठाया गया',
    'driver.droppedOff': 'उतारा गया',
    'driver.busTracking': 'बस ट्रैकिंग',
    'driver.trackChildren': 'अपने बच्चों की बस को रियल-टाइम में ट्रैक करें',
    'driver.live': 'लाइव',
    'driver.minutes': 'मिनट',
    
    // Transport
    'transport.manage': 'स्कूल परिवहन और बसों का प्रबंधन करें',
    'transport.addBus': 'बस जोड़ें',
    'transport.totalBuses': 'कुल बसें',
    'transport.activeBuses': 'सक्रिय बसें',
    'transport.totalCapacity': 'कुल क्षमता',
    'transport.currentStudents': 'वर्तमान छात्र',
    'transport.students': 'छात्र',
    'transport.lastLocation': 'अंतिम स्थान',
    'transport.updated': 'अपडेट किया गया',
    'transport.route': 'मार्ग',
    'transport.editBus': 'बस जानकारी संपादित करें',
    'transport.driverName': 'ड्राइवर का नाम',
    'transport.driverPhone': 'ड्राइवर का फोन',
    'transport.busNumber': 'बस नंबर',
    
    // Common
    'common.language': 'भाषा',
    'common.english': 'English',
    'common.arabic': 'العربية',
    'common.hindi': 'हिन्दी',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.add': 'जोड़ें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.export': 'निर्यात करें',
    'common.import': 'आयात करें',
    'common.actions': 'कार्रवाई',
    'common.view': 'देखें',
    'common.download': 'डाउनलोड करें',
    'common.upload': 'अपलोड करें',
    'common.date': 'तारीख',
    'common.time': 'समय',
    'common.status': 'स्थिति',
    'common.active': 'सक्रिय',
    'common.inactive': 'निष्क्रिय',
    'common.pending': 'लंबित',
    'common.completed': 'पूर्ण',
    'common.close': 'बंद करें',
    'common.currency': 'OMR',
    'common.name': 'नाम',
    'common.nameAr': 'नाम (अरबी)',
    'common.nameHi': 'नाम (हिंदी)',
    'common.email': 'ईमेल',
    'common.phone': 'फोन',
    'common.class': 'कक्षा',
    'common.address': 'पता',
    'common.bloodGroup': 'रक्त समूह',
    'common.allergies': 'एलर्जी',
    'common.emergencyContact': 'आपातकालीन संपर्क',
    'common.dateOfBirth': 'जन्म तिथि',
    'common.parentName': 'अभिभावक का नाम',
    'common.parentPhone': 'अभिभावक का फोन',
    'common.notes': 'नोट्स',
    'common.importantNotes': 'महत्वपूर्ण नोट्स',
    'common.contactInfo': 'संपर्क जानकारी',
    'common.homeAddress': 'घर का पता',
    'common.viewOnMap': 'मानचित्र पर देखें',
    'common.call': 'कॉल करें',
    'common.maintenance': 'रखरखाव',
    'common.capacity': 'क्षमता',
    'common.subject': 'विषय',
    'common.teacher': 'शिक्षक',
    'common.room': 'कक्ष',
    'common.day': 'दिन',
    'common.duration': 'अवधि',
    'common.examType': 'परीक्षा प्रकार',
    'common.newMessage': 'नया संदेश',
    'common.typeMessage': 'अपना संदेश लिखें...',
    'common.selectConversation': 'संदेश भेजने के लिए वार्तालाप चुनें',
    'common.messageSent': 'संदेश भेजा गया',
    'common.messageSentDesc': 'आपका संदेश सफलतापूर्वक भेजा गया',
    'common.searchConversations': 'वार्तालाप खोजें...',
    'common.calendar': 'कैलेंडर',
    'common.deleted': 'हटाया गया',
    'common.deletedDesc': 'आइटम सफलतापूर्वक हटाया गया',
    'common.savedSuccessfully': 'सफलतापूर्वक सहेजा गया',
    'common.profileUpdated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई',
    'common.welcomeDashboard': 'अपने स्कूल प्रबंधन डैशबोर्ड में पुनः स्वागत है',
    'common.fromLastMonth': 'पिछले महीने से',
    'common.recentActivities': 'हाल की गतिविधियाँ',
    'common.upcomingEvents': 'आगामी कार्यक्रम',
    'common.morningRoute': 'सुबह का मार्ग',
    'common.parentContact': 'अभिभावक संपर्क',
    'common.homeLocation': 'घर का स्थान',
    'common.openInMaps': 'मानचित्र में खोलें',
    'common.studentInfo': 'छात्र जानकारी',
    'common.addClass': 'कक्षा जोड़ें',
    'common.classTeacher': 'कक्षा शिक्षक',
    'common.classesToday': 'आज की कक्षाएँ',
    'common.classSchedule': 'कक्षा समय सारणी',
    'common.examSchedule': 'परीक्षा समय सारणी',
    'common.addSchedule': 'समय सारणी जोड़ें',
    'common.addExam': 'परीक्षा जोड़ें',
    'common.addClassSchedule': 'कक्षा समय सारणी जोड़ें',
    'common.addExamSchedule': 'परीक्षा समय सारणी जोड़ें',
    'common.emailCreated': 'ईमेल खाता बनाया गया',
    'common.emailCreatedDesc': 'ईमेल खाता सफलतापूर्वक बनाया गया',
    'common.noPermission': 'आपको इस पृष्ठ को देखने की अनुमति नहीं है',
    'common.manageClasses': 'कक्षा समय सारणी और परीक्षाएँ प्रबंधित करें',
    'common.communicateStaff': 'शिक्षकों और स्कूल स्टाफ से संवाद करें',
    'common.driverDashboard': 'ड्राइवर डैशबोर्ड',
    'common.busRouteManagement': 'बस मार्ग प्रबंधन और छात्र ट्रैकिंग',
    'common.teacherDashboard': 'शिक्षक डैशबोर्ड',
    'common.manageYourClasses': 'अपनी कक्षाएँ प्रबंधित करें और छात्र प्रगति ट्रैक करें',
    'common.barcode': 'बारकोड',
    'common.nfcId': 'NFC आईडी',
    'common.rollNumber': 'रोल नंबर',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.approved': 'स्वीकृत',
    'common.rejected': 'अस्वीकृत',
    'common.available': 'उपलब्ध',
    'common.notAvailable': 'उपलब्ध नहीं',
    'common.id': 'आईडी',
    'common.grade': 'कक्षा',
    'common.section': 'अनुभाग',
    'common.viewDetails': 'विवरण देखें',
    'common.noRecords': 'कोई रिकॉर्ड नहीं मिला',
    'common.noStudentsOnboard': 'कोई छात्र बोर्ड पर नहीं',
    'common.noRecordsToday': 'आज कोई रिकॉर्ड नहीं',
    
    // Footer
    'footer.allRightsReserved': 'सर्वाधिकार सुरक्षित',
    
    // Log levels
    'log.info': 'जानकारी',
    'log.warn': 'चेतावनी',
    'log.error': 'त्रुटि',
    'log.debug': 'डीबग',
    
    // Status badges
    'status.draft': 'ड्राफ्ट',
    'status.pendingApproval': 'अनुमोदन लंबित',
    'status.approved': 'स्वीकृत',
    'status.rejected': 'अस्वीकृत',
    'status.active': 'सक्रिय',
    'status.inactive': 'निष्क्रिय',
    'status.available': 'उपलब्ध',
    'status.notAvailable': 'उपलब्ध नहीं',
    'status.present': 'उपस्थित',
    'status.absent': 'अनुपस्थित',
    'status.late': 'देर से',
    'status.notMarked': 'चिह्नित नहीं',
    
    // Stats
    'stats.totalStudents': 'कुल छात्र',
    'stats.totalTeachers': 'कुल शिक्षक',
    'stats.attendance': 'उपस्थिति दर',
    'stats.busesActive': 'सक्रिय बसें',
    'stats.pendingFees': 'लंबित शुल्क',
    
    // Features
    'feature.busTracking': 'बस ट्रैकिंग',
    'feature.wallet': 'डिजिटल वॉलेट',
    'feature.payments': 'भुगतान',
    'feature.canteen': 'कैंटीन प्रबंधन',
    
    // Schedule
    'schedule.mathematics': 'गणित',
    'schedule.physics': 'भौतिक विज्ञान',
    'schedule.english': 'अंग्रेजी',
    'schedule.arabic': 'अरबी',
    'schedule.hindi': 'हिन्दी',
    'schedule.chemistry': 'रसायन विज्ञान',
    'schedule.history': 'इतिहास',
    'schedule.pe': 'शारीरिक शिक्षा',
    'schedule.break': 'अवकाश',
    'schedule.room': 'कक्ष',
    'schedule.lab': 'प्रयोगशाला',
    'schedule.canteen': 'कैंटीन',
    'schedule.sportsHall': 'खेल हॉल',
    'schedule.downloadSchedule': 'समय सारणी डाउनलोड करें',
    'schedule.todaySchedule': 'आज की समय सारणी',
    'schedule.scheduleSummary': 'समय सारणी सारांश',
    'schedule.classes': 'कक्षाएँ',
    'schedule.totalHours': 'कुल घंटे',
    'schedule.manageSchedules': 'दैनिक समय सारणी देखें और प्रबंधित करें',
    
    // Grades
    'grades.subject': 'विषय',
    'grades.grade': 'अंक',
    'grades.score': 'स्कोर',
    'grades.date': 'तारीख',
    'grades.teacher': 'शिक्षक',
    'grades.exam': 'परीक्षा',
    'grades.assignment': 'असाइनमेंट',
    'grades.project': 'प्रोजेक्ट',
    'grades.midterm': 'मध्यावधि',
    'grades.final': 'अंतिम',
    'grades.quiz': 'क्विज़',
    'grades.homework': 'गृहकार्य',
    'grades.classwork': 'कक्षा कार्य',
    'grades.recentGrades': 'हाल के अंक',
    'grades.examType': 'परीक्षा प्रकार',
    'grades.notes': 'नोट्स',
    'grades.approve': 'स्वीकृत करें',
    'grades.addGrade': 'अंक जोड़ें',
    'grades.editGrade': 'अंक संपादित करें',
    'grades.selectClass': 'कक्षा चुनें',
    'grades.selectStudent': 'छात्र चुनें',
    'grades.selectSubject': 'विषय चुनें',
    'grades.enterScore': 'स्कोर दर्ज करें',
    'grades.enterNotes': 'नोट्स दर्ज करें',
    
    // Homework
    'homework.pendingHomework': 'लंबित गृहकार्य',
    'homework.dueDate': 'जमा करने की तारीख',
    'homework.submit': 'जमा करें',
    'homework.submitted': 'जमा किया गया',
    'homework.notSubmitted': 'जमा नहीं किया',
    
    // Exams
    'exams.upcomingExams': 'आगामी परीक्षाएँ',
    'exams.examDate': 'परीक्षा तिथि',
    'exams.examTime': 'परीक्षा समय',
    'exams.examLocation': 'परीक्षा स्थान',
    
    // Time
    'time.minutes': 'मिनट',
    'time.hours': 'घंटे',
    'time.days': 'दिन',
    'time.ago': 'पहले',
    'time.min': 'मिनट',
    'time.hrs': 'घंटे',
    
    // Student Profile
    'profile.studentWallet': 'छात्र वॉलेट',
    'profile.studentHomework': 'छात्र गृहकार्य',
    'profile.studentNotes': 'नोट्स',
    'profile.studentSchedules': 'समय सारणी',
    'profile.viewGrades': 'अंक देखें',
    'profile.manageWallet': 'वॉलेट प्रबंधित करें',

    // Payroll - Hindi translations
    'Employee ID': 'कर्मचारी आईडी',
    'Base Salary': 'मूल वेतन',
    'Configure': 'कॉन्फ़िगर करें',
    'Payment Frequency': 'भुगतान आवृत्ति',
    'Teacher Payroll Configuration': 'शिक्षक वेतन कॉन्फ़िगरेशन',
    'Teacher': 'शिक्षक',
    'Period': 'अवधि',
    'Net Salary': 'शुद्ध वेतन',
    'Payment Date': 'भुगतान तिथि',
    'Process Payment': 'भुगतान प्रक्रिया',
    'Configure Payroll': 'वेतन कॉन्फ़िगर करें',
    'Set up payroll configuration for': 'के लिए वेतन कॉन्फ़िगरेशन सेट करें',
    'Base Salary (OMR)': 'मूल वेतन (OMR)',
    'Hourly Rate (OMR) - Optional': 'प्रति घंटा दर (OMR) - वैकल्पिक',
    'Monthly': 'मासिक',
    'Bi-Weekly': 'पाक्षिक',
    'Weekly': 'साप्ताहिक',
    'Bank Account (Optional)': 'बैंक खाता (वैकल्पिक)',
    'Saving...': 'सहेज रहे हैं...',
    'Calculate': 'गणना करें',
    'Calculate Salary': 'वेतन की गणना करें',
    'Calculate salary for': 'के लिए वेतन की गणना करें',
    'Month': 'महीना',
    'Year': 'वर्ष',
    'Calculating...': 'गणना कर रहे हैं...',
    'Process Salary Payment': 'वेतन भुगतान प्रक्रिया',
    'Confirm salary payment processing': 'वेतन भुगतान प्रक्रिया की पुष्टि करें',
    'Payment Confirmation': 'भुगतान पुष्टि',
    'You are about to transfer': 'आप स्थानांतरित करने वाले हैं',
    'to': 'को',
    'Working Days': 'कार्य दिवस',
    'Present Days': 'उपस्थिति के दिन',
    'Deductions': 'कटौती',
    'Bonuses': 'बोनस',
    'Processing...': 'प्रोसेसिंग...',
    'Confirm Payment': 'भुगतान की पुष्टि करें',
    'Payroll Records': 'वेतन रिकॉर्ड',
    'Teacher Attendance': 'शिक्षक उपस्थिति',
    'Check In': 'चेक इन',
    'Check Out': 'चेक आउट',
    'Total Hours': 'कुल घंटे',
    'Leave Requests': 'छुट्टी अनुरोध',
    'Leave Type': 'छुट्टी का प्रकार',
    'Start Date': 'प्रारंभ तिथि',
    'End Date': 'समाप्ति तिथि',
    'Reason': 'कारण',
    'Vacation': 'छुट्टी',
    'Sick Leave': 'बीमारी की छुट्टी',
    'Personal': 'व्यक्तिगत',
    'Emergency': 'आपातकालीन',
    'Request Leave': 'छुट्टी का अनुरोध करें',
    'Payroll Reports': 'वेतन रिपोर्ट',
    'Generate Report': 'रिपोर्ट बनाएं',
    'Report Type': 'रिपोर्ट प्रकार',
    'Salary Summary': 'वेतन सारांश',
    'Attendance Report': 'उपस्थिति रिपोर्ट',
    'Deductions Report': 'कटौती रिपोर्ट',
    'Select Period': 'अवधि चुनें',
    'Current Month': 'वर्तमान महीना',
    'Last Month': 'पिछला महीना',
    'Custom Range': 'कस्टम रेंज',
    'Download PDF': 'PDF डाउनलोड करें',
    'Total Salaries': 'कुल वेतन',
    'Total Deductions': 'कुल कटौती',
    'Total Bonuses': 'कुल बोनस',
    'Net Total': 'शुद्ध कुल',
    'Payroll Overview': 'वेतन अवलोकन',
    'Teachers Payroll': 'शिक्षक वेतन',
    'Payroll Configuration': 'वेतन कॉन्फ़िगरेशन',
    'Payment Status': 'भुगतान स्थिति',
    'Paid': 'भुगतान किया',
    'Pending': 'लंबित',
    'Approved': 'स्वीकृत',
    'Rejected': 'अस्वीकृत',

    // Network Status
    'network.connected': 'इंटरनेट से जुड़े हैं',
    'network.disconnected': 'इंटरनेट कनेक्शन नहीं है',
    'network.backOnline': 'आप वापस ऑनलाइन हैं',
    'network.offline': 'आप ऑफ़लाइन हैं',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'ar' || savedLang === 'hi')) {
      setLanguageState(savedLang);
      document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = savedLang;
      document.documentElement.style.fontFamily = savedLang === 'ar' ? 
        'Cairo, sans-serif' : savedLang === 'hi' ? 'Noto Sans Devanagari, sans-serif' : 'Inter, sans-serif';
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    document.documentElement.style.fontFamily = lang === 'ar' ? 
      'Cairo, sans-serif' : lang === 'hi' ? 'Noto Sans Devanagari, sans-serif' : 'Inter, sans-serif';
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t,
      dir: language === 'ar' ? 'rtl' : 'ltr'
    }}>
      {children}
    </LanguageContext.Provider>
  );
};
