import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { corsHeaders } from '../_shared/cors.ts';

const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { title, description, width = 390, height = 844 } = await req.json();

    if (!title && !description) {
      return new Response(
        JSON.stringify({ error: 'Title or description is required for AI generation' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`Generating screenshot for: ${title}`);

    // Create detailed prompt for AI image generation
    const prompt = `Generate a mobile app screenshot mockup for an educational school management system.

Screen: ${title}
${description ? `Description: ${description}` : ''}

Style requirements:
- Modern iOS/mobile interface design
- Clean, professional layout
- iPhone 15 screen proportions (390x844px)
- Proper status bar at top with time, battery, signal
- Bottom navigation bar if applicable
- Use a professional color scheme with blues, whites, and accent colors
- Include realistic UI elements: buttons, cards, lists, icons
- Text should be legible and properly sized
- Include relevant icons and imagery
- Make it look like a real, polished production app
- Ultra high resolution, crisp and clear
- Professional gradient backgrounds where appropriate

Generate a pixel-perfect, production-quality mobile app screenshot.`;

    // Call Lovable AI to generate the screenshot
    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        modalities: ["image", "text"]
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Lovable AI API error:', errorText);
      throw new Error(`AI API returned ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const generatedImageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!generatedImageUrl) {
      console.error('No image in AI response:', JSON.stringify(data));
      throw new Error('No image generated by AI');
    }

    console.log(`Screenshot generated successfully`);

    return new Response(
      JSON.stringify({ 
        success: true,
        imageBase64: generatedImageUrl, // Already in data:image/png;base64,... format
        width: width * 3, // 3x for retina
        height: height * 3,
        timestamp: new Date().toISOString()
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error generating screenshot:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
